<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>ETL_SQL.Reporting</RootNamespace>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ETL-SQL.Core\ETL-SQL.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="QuestPDF" />
    <PackageReference Include="Spectre.Console" />
  </ItemGroup>

</Project>
