// Browser-side lint gate.
//
// The companion to `tsconfig.json` in this directory, over exactly the same sources. The type gate
// answers "does this name exist and does this object have that field"; this one answers the
// questions a checker does not ask — a value assigned and never read, a `catch` block that
// swallows, a duplicated object key. Between them they cover the defect profile v0.19.0 measured:
// ten of that release's twelve live browser defects were scope or syntax errors, and `no-undef`
// and `no-dupe-keys` alone would have found them in seconds.
//
// Nothing here emits, bundles or rewrites a file. The shipped browser code stays plain `.js`.
//
// The file list obeys the same two rules as `tsconfig.json`, for the same reasons:
//   1. Only canonical sources are linted. Host copies under a wwwroot are generated by
//      `node scripts/sync-assets.js`; linting a copy would report every finding twice and invite
//      a "fix" to a file that the next sync overwrites.
//   2. Vendored bundles are not ours to fix.
//
// `scripts/lint-browser.mjs` is the gate that runs this. Run ESLint directly and you get the raw
// findings with no baseline comparison, which is useful while fixing and is not what CI runs.

import js from './scripts/lint/node_modules/@eslint/js/src/index.js';
import globals from './scripts/lint/node_modules/globals/index.js';

/**
 * Sources loaded with a plain `<script src>` rather than `<script type="module">`.
 *
 * They are scripts, not modules: top-level `var` reaches `window`, top-level `this` is defined,
 * and the file is not in strict mode unless it says so. Parsing them as modules would report
 * their globals as undefined and their top-level `this` as an error, so the distinction is not
 * cosmetic. A file that grows an `import` has become a module and belongs out of this list.
 */
const classicScripts = [
    'src/ETL-SQL.ReportRuntime/Resources/Shared/feedback.js',
    'src/ETL-SQL.ReportRuntime/Resources/Shared/report-runtime.js',
    'src/ETL-SQL.Portal/wwwroot/js/control-plane.js',
    'src/ETL-SQL.Portal/wwwroot/js/native-charts.js',
];

export default [
    {
        ignores: [
            '**/node_modules/**',
            '**/bin/**',
            '**/obj/**',
            '.worktrees/**',

            // Vendored bundles: arrow, tabulator, the CodeMirror bundle.
            '**/*.min.js',

            // Generated host copies of the canonical shared assets. See scripts/sync-assets.js.
            'src/ETL-SQL.Portal/wwwroot/js/report-runtime.js',
            'src/ETL-SQL.Portal/wwwroot/js/feedback.js',
        ],
    },
    {
        files: [
            'src/ETL-SQL.ReportRuntime/Resources/Shared/**/*.js',
            'src/ETL-SQL.Portal/wwwroot/js/**/*.js',
        ],
        ...js.configs.recommended,
        languageOptions: {
            ecmaVersion: 2022,
            sourceType: 'module',
            globals: {
                ...globals.browser,

                // The ESLint half of `types/browser-globals.d.ts`. Same rule applies: everything
                // here is a real global something actually assigns, and nothing speculative
                // belongs in it. An entry added to quiet an error is an entry that stops the gate
                // reporting the next real one.
                ETLSQLFeedback: 'readonly',
                nativeCharts: 'readonly',
                Tabulator: 'readonly',
                arrow: 'readonly',
                acquireVsCodeApi: 'readonly',
            },
        },
    },
    {
        files: classicScripts,
        languageOptions: { sourceType: 'script' },
    },
];
