<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>ETL_SQL.Engine</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Apache.Arrow" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="PgpCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ETL-SQL.Analysis\ETL-SQL.Analysis.csproj" />
    <ProjectReference Include="..\ETL-SQL.Core\ETL-SQL.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ETL-SQL.Tests, PublicKey=$(AssemblyPublicKey)" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="ETL_SQL.Core" />
    <Using Include="ETL_SQL.Core.Parser" />
  </ItemGroup>

</Project>
