<Project Sdk="Microsoft.NET.Sdk">
 
   <PropertyGroup>
     <RootNamespace>ETL_SQL.Engine</RootNamespace>
   </PropertyGroup>
 
   <ItemGroup>
     <PackageReference Include="Apache.Arrow" Version="16.0.0" />
     <PackageReference Include="PgpCore" Version="6.6.0" />
     <PackageReference Include="Spectre.Console" Version="0.54.0" />
   </ItemGroup>
 
   <ItemGroup>
     <ProjectReference Include="..\ETL-SQL.Core\ETL-SQL.Core.csproj" />
   </ItemGroup>
 
   <ItemGroup>
     <InternalsVisibleTo Include="ETL-SQL.Tests" />
   </ItemGroup>
 
 
   <ItemGroup>
     <Using Include="ETL_SQL.Core" />
     <Using Include="ETL_SQL.Core.Parser" />
   </ItemGroup>
 
 </Project>
