using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;

namespace ETL_SQL.Reporting.Authoring;

/// <summary>Generates a new Report-SQL presentation scaffold when no source text exists to patch.</summary>
public sealed class DesignerScriptGenerationService
{
    private const int GridCols = 12;

    public string Generate(DesignerAuthoringState state, string? lineEnding = null)
    {
        var nl = lineEnding ?? Environment.NewLine;
        var sb = new StringBuilder();
        AppendLine(sb, "-- Generated by ETL-SQL Report Designer", nl);
        AppendLine(sb, string.Empty, nl);

        if (state.ReportStyle is not null)
        {
            var styleOptions = BuildReportStyleOptions(state.ReportStyle);
            if (styleOptions.Count > 0)
            {
                AppendLine(sb, $"SET REPORT STYLE ({string.Join(", ", styleOptions)});", nl);
                AppendLine(sb, string.Empty, nl);
            }
        }

        foreach (var dataset in state.Datasets ?? [])
        {
            var name = NormalizeDatasetName(dataset.Name);
            var query = string.IsNullOrWhiteSpace(dataset.Query)
                ? "SELECT 1 AS Placeholder"
                : dataset.Query.Trim().TrimEnd(';');
            AppendLine(sb, $"CREATE DATASET {name} AS (", nl);
            AppendLine(sb, $"  {query}", nl);
            AppendLine(sb, ");", nl);
            AppendLine(sb, string.Empty, nl);
        }

        var emitted = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        var pageNumber = 0;
        foreach (var page in state.Pages ?? [])
        {
            pageNumber++;
            var pageName = SanitizeName(string.IsNullOrWhiteSpace(page.Name) ? $"Page{pageNumber}" : page.Name);
            var visuals = page.Visuals ?? [];

            foreach (var visual in visuals)
            {
                var name = SanitizeName(visual.Name, visual.Id);
                if (!emitted.Add(name))
                    continue;
                AppendLine(sb, GenerateElement(visual, visuals, nl, isScaffold: true), nl);
                AppendLine(sb, string.Empty, nl);
            }

            AppendLine(sb, GeneratePage(pageName, page.Mode, visuals, nl), nl);
            AppendLine(sb, string.Empty, nl);
        }

        // Bookmarks come last: they reference pages and named objects, so emitting them after the
        // declarations keeps a generated scaffold readable top to bottom.
        foreach (var bookmark in state.Bookmarks ?? [])
        {
            var text = GenerateBookmark(bookmark, nl);
            if (text.Length == 0) continue;
            AppendLine(sb, text, nl);
            AppendLine(sb, string.Empty, nl);
        }

        return sb.ToString();
    }

    /// <summary>
    /// Emits one <c>CREATE BOOKMARK</c>. Parameter values are written through verbatim, because the
    /// designer carries them as authored source text — quoting a number here is exactly the bug the
    /// typed bookmark AST exists to prevent.
    /// </summary>
    internal static string GenerateBookmark(DesignerAuthoringBookmark bookmark, string nl)
    {
        var clauses = new List<string>();
        if (!string.IsNullOrWhiteSpace(bookmark.Title))
            clauses.Add($"    TITLE = '{EscapeStr(bookmark.Title!)}'");

        var parameters = (bookmark.Parameters ?? []).Where(p => !string.IsNullOrWhiteSpace(p.Name)).ToList();
        if (parameters.Count > 0)
        {
            var assignments = parameters.Select(p =>
                $"        {(p.Name.StartsWith('@') ? p.Name : "@" + p.Name)} = {p.Value?.Trim()}");
            clauses.Add($"    PARAMETERS ({nl}{string.Join("," + nl, assignments)}{nl}    )");
        }

        if (!string.IsNullOrWhiteSpace(bookmark.Page))
            clauses.Add($"    PAGE = {SanitizeName(bookmark.Page!)}");

        var stateEntries = (bookmark.State ?? []).Where(s => !string.IsNullOrWhiteSpace(s.ObjectName)).ToList();
        if (stateEntries.Count > 0)
        {
            var entries = stateEntries.Select(s =>
                $"        {SanitizeName(s.ObjectName)}.{(s.Property ?? "VISIBLE").ToUpperInvariant()} = {(s.On ? "ON" : "OFF")}");
            clauses.Add($"    STATE ({nl}{string.Join("," + nl, entries)}{nl}    )");
        }

        if (bookmark.IsDefault)
            clauses.Add("    DEFAULT = ON");

        // A bookmark that sets nothing is not a bookmark; emitting an empty body would only produce
        // a script that no longer parses.
        if (clauses.Count == 0) return string.Empty;

        var sb = new StringBuilder();
        AppendLine(sb, $"CREATE BOOKMARK {SanitizeName(bookmark.Name, bookmark.Id)} AS (", nl);
        AppendLine(sb, string.Join("," + nl, clauses), nl);
        sb.Append(");");
        return sb.ToString();
    }

    internal static string GenerateElement(
        DesignerAuthoringVisual visual,
        IReadOnlyList<DesignerAuthoringVisual> allVisuals,
        string nl,
        bool isScaffold = false)
    {
        var sb = new StringBuilder();
        var name = SanitizeName(visual.Name, visual.Id);

        if (string.Equals(visual.Type, "CONTAINER", StringComparison.OrdinalIgnoreCase))
        {
            var containerType = visual.Options.TryGetValue("CONTAINER_TYPE", out var type) ? type : "BOX";
            AppendLine(sb, $"CREATE CONTAINER {name} AS {containerType.ToUpperInvariant()} (", nl);
            if (!string.IsNullOrWhiteSpace(visual.Title))
                AppendLine(sb, $"    TITLE = '{EscapeStr(visual.Title)}',", nl);

            var children = allVisuals.Where(child => child.ContainerId == visual.Id).ToList();
            if (children.Count > 0)
            {
                AppendLine(sb, "    LAYOUT (", nl);
                var slots = children.Select((_, index) => GetSlotLetter(index)).ToList();
                AppendLine(sb, $"        STRUCTURE = '{string.Join(" ", slots)}',", nl);
                AppendLine(sb, "        MAP (", nl);
                for (var index = 0; index < children.Count; index++)
                {
                    var suffix = index < children.Count - 1 ? "," : string.Empty;
                    AppendLine(sb,
                        $"            '{slots[index]}' = {SanitizeName(children[index].Name, children[index].Id)}{suffix}", nl);
                }
                AppendLine(sb, "        )", nl);
                AppendLine(sb, "    )", nl);
            }
            sb.Append(");");
            return sb.ToString();
        }

        if (string.Equals(visual.Type, "BUTTON", StringComparison.OrdinalIgnoreCase))
        {
            var buttonType = visual.Options.TryGetValue("BUTTON_TYPE", out var type) ? type : "REFRESH";
            AppendLine(sb, $"CREATE BUTTON {name} AS (", nl);
            if (!string.IsNullOrWhiteSpace(visual.Title))
                AppendLine(sb, $"    TITLE = '{EscapeStr(visual.Title)}',", nl);
            AppendLine(sb, $"    OPTIONS (BUTTON_TYPE = '{EscapeStr(buttonType)}')", nl);
            sb.Append(");");
            return sb.ToString();
        }

        AppendLine(sb, $"CREATE VISUAL {name} AS {GetVisualTypeKeyword(visual.Type)} (", nl);
        if (!string.IsNullOrWhiteSpace(visual.Title))
            AppendLine(sb, $"    TITLE = '{EscapeStr(visual.Title)}',", nl);

        if (visual.Options.TryGetValue("inline_source", out var inlineSource) && !string.IsNullOrWhiteSpace(inlineSource))
            AppendLine(sb, $"    SOURCE = {inlineSource},", nl);
        else if (!string.IsNullOrWhiteSpace(visual.Dataset))
            AppendLine(sb, $"    SOURCE = {NormalizeDatasetName(visual.Dataset)},", nl);

        if (visual.Options.TryGetValue("advanced_chart", out var advancedChart) && !string.IsNullOrWhiteSpace(advancedChart))
        {
            var chartBlock = advancedChart.Trim().TrimEnd(',');
            if (!chartBlock.StartsWith("CHART", StringComparison.OrdinalIgnoreCase))
                chartBlock = $"CHART ({nl}        {chartBlock}{nl}    )";
            AppendLine(sb, $"    {chartBlock},", nl);
        }
        else if (isScaffold && string.Equals(visual.Type, "CUSTOM", StringComparison.OrdinalIgnoreCase))
        {
            AppendLine(sb, $"    CHART ({nl}        COORDINATE (TYPE = CARTESIAN),{nl}        LAYERS ({nl}            main = RECT ({nl}                ENCODINGS ({nl}                    X = category (TYPE = NOMINAL),{nl}                    Y = value (TYPE = QUANTITATIVE){nl}                ){nl}            ){nl}        ){nl}    ),", nl);
        }

        var mappings = visual.Mappings
            .Where(mapping => !string.IsNullOrWhiteSpace(mapping.Value))
            .Select(mapping => $"{mapping.Key.ToUpperInvariant()} = {mapping.Value}")
            .ToList();
        if (mappings.Count > 0)
            AppendLine(sb, $"    MAPPINGS ({string.Join(", ", mappings)}),", nl);

        var regularOptions = visual.Options
            .Where(option => !IsReservedOption(option.Key))
            .Select(option => $"{option.Key.ToUpperInvariant()} = '{EscapeStr(option.Value)}'")
            .ToList();
        if (regularOptions.Count > 0)
            AppendLine(sb, $"    OPTIONS ({string.Join(", ", regularOptions)}),", nl);

        var actions = visual.Options
            .Where(option => option.Key.StartsWith("action:", StringComparison.OrdinalIgnoreCase))
            .Select(option => $"{option.Key["action:".Length..].ToUpperInvariant()} = {option.Value}")
            .ToList();
        if (actions.Count > 0)
            AppendLine(sb, $"    ACTIONS ({string.Join(", ", actions)}),", nl);

        var interactions = visual.Options
            .Where(option => option.Key.StartsWith("interaction:", StringComparison.OrdinalIgnoreCase))
            .Select(option => $"{option.Key["interaction:".Length..].ToUpperInvariant()} = {option.Value}")
            .ToList();
        if (interactions.Count > 0)
            AppendLine(sb, $"    INTERACTIONS ({string.Join(", ", interactions)}),", nl);

        if (visual.Options.TryGetValue("cascade", out var cascade) && !string.IsNullOrWhiteSpace(cascade))
            AppendLine(sb, $"    {cascade.Trim().TrimEnd(',')},", nl);

        var styleOptions = new List<string>();
        if (visual.Options.TryGetValue("WIDTH", out var width) && !string.IsNullOrWhiteSpace(width))
            styleOptions.Add($"WIDTH = '{EscapeStr(width)}'");
        if (visual.Options.TryGetValue("HEIGHT", out var height) && !string.IsNullOrWhiteSpace(height))
            styleOptions.Add($"HEIGHT = '{EscapeStr(height)}'");
        if (styleOptions.Count > 0)
            AppendLine(sb, $"    STYLE ({string.Join(", ", styleOptions)}),", nl);

        TrimTrailingComma(sb, nl);
        sb.Append(");");
        return sb.ToString();
    }

    internal static string GeneratePage(
        string pageName,
        string mode,
        IReadOnlyList<DesignerAuthoringVisual> visuals,
        string nl)
    {
        var modeKeyword = string.Equals(mode, "Paginated", StringComparison.OrdinalIgnoreCase)
            ? "PAGINATED"
            : "DASHBOARD";
        if (visuals.Count == 0)
            return $"CREATE PAGE [{pageName}] AS {modeKeyword} ( LAYOUT ( STRUCTURE = '.' ) );";

        var sb = new StringBuilder();
        AppendLine(sb, $"CREATE PAGE [{pageName}] AS {modeKeyword} (", nl);
        AppendLine(sb, "    LAYOUT (", nl);
        AppendLine(sb, $"        STRUCTURE = '{EscapeStr(BuildStructure(visuals))}',", nl);
        AppendLine(sb, "        MAP (", nl);
        for (var index = 0; index < visuals.Count; index++)
        {
            var suffix = index < visuals.Count - 1 ? "," : string.Empty;
            AppendLine(sb,
                $"            '{GetSlotLetter(index)}' = {SanitizeName(visuals[index].Name, visuals[index].Id)}{suffix}", nl);
        }
        AppendLine(sb, "        )", nl);
        AppendLine(sb, "    )", nl);
        sb.Append(");");
        return sb.ToString();
    }

    internal static List<string> BuildReportStyleOptions(DesignerAuthoringReportStyle style)
    {
        var options = new List<string>();
        if (!string.IsNullOrWhiteSpace(style.Theme)) options.Add($"THEME = '{EscapeStr(style.Theme)}'");
        if (!string.IsNullOrWhiteSpace(style.Accent)) options.Add($"ACCENT = '{EscapeStr(style.Accent)}'");
        if (!string.IsNullOrWhiteSpace(style.Background)) options.Add($"BACKGROUND = '{EscapeStr(style.Background)}'");
        if (!string.IsNullOrWhiteSpace(style.Surface)) options.Add($"SURFACE = '{EscapeStr(style.Surface)}'");
        if (!string.IsNullOrWhiteSpace(style.Text)) options.Add($"TEXT = '{EscapeStr(style.Text)}'");
        return options;
    }

    internal static string BuildStructure(IReadOnlyList<DesignerAuthoringVisual> visuals)
    {
        if (visuals.Count == 0) return ".";
        var maxRow = visuals.Max(visual => visual.GridRow + visual.GridRowSpan - 1);
        var usedColumns = Math.Min(GridCols, visuals.Max(visual => visual.GridCol + visual.GridColSpan - 1));
        var grid = new string[maxRow, usedColumns];
        for (var row = 0; row < maxRow; row++)
            for (var column = 0; column < usedColumns; column++)
                grid[row, column] = ".";

        for (var index = 0; index < visuals.Count; index++)
        {
            var visual = visuals[index];
            var slot = GetSlotLetter(index);
            for (var row = visual.GridRow - 1; row < visual.GridRow - 1 + visual.GridRowSpan && row < maxRow; row++)
                for (var column = visual.GridCol - 1; column < visual.GridCol - 1 + visual.GridColSpan && column < usedColumns; column++)
                    grid[row, column] = slot;
        }

        var rows = new List<string>(maxRow);
        for (var row = 0; row < maxRow; row++)
        {
            var slots = new List<string>();
            for (var column = 0; column < usedColumns; column++)
                if (slots.Count == 0 || slots[^1] != grid[row, column])
                    slots.Add(grid[row, column]);
            var value = string.Join(" ", slots);
            if (rows.Count == 0 || rows[^1] != value)
                rows.Add(value);
        }
        return string.Join(" / ", rows);
    }

    internal static string GetSlotLetter(int index)
    {
        var result = string.Empty;
        for (var value = index; value >= 0; value = value / 26 - 1)
            result = (char)('A' + value % 26) + result;
        return result;
    }

    internal static string SanitizeName(string? name, string? fallback = null)
    {
        var input = string.IsNullOrWhiteSpace(name) ? fallback : name;
        if (string.IsNullOrWhiteSpace(input)) return "visual1";
        var safe = Regex.Replace(input.Trim(), @"[^a-zA-Z0-9_]", "_");
        return char.IsLetter(safe[0]) ? safe : "v_" + safe;
    }

    internal static string NormalizeDatasetName(string? name)
    {
        var value = (name ?? string.Empty).Trim();
        if (value.StartsWith('&') || value.StartsWith('#')) value = value[1..];
        return "&" + SanitizeName(value);
    }

    internal static string GetVisualTypeKeyword(string? type) => (type ?? string.Empty).ToUpperInvariant() switch
    {
        "HORIZONTALBAR" => "HBAR",
        var value => value
    };

    internal static string EscapeStr(string value) => value.Replace("'", "''");

    private static bool IsReservedOption(string key) =>
        string.Equals(key, "WIDTH", StringComparison.OrdinalIgnoreCase)
        || string.Equals(key, "HEIGHT", StringComparison.OrdinalIgnoreCase)
        || string.Equals(key, "CONTAINER_TYPE", StringComparison.OrdinalIgnoreCase)
        || string.Equals(key, "BUTTON_TYPE", StringComparison.OrdinalIgnoreCase)
        || string.Equals(key, "inline_source", StringComparison.OrdinalIgnoreCase)
        || string.Equals(key, "cascade", StringComparison.OrdinalIgnoreCase)
        || string.Equals(key, "advanced_chart", StringComparison.OrdinalIgnoreCase)
        || key.StartsWith("action:", StringComparison.OrdinalIgnoreCase)
        || key.StartsWith("interaction:", StringComparison.OrdinalIgnoreCase);

    private static void AppendLine(StringBuilder builder, string value, string lineEnding) =>
        builder.Append(value).Append(lineEnding);

    private static void TrimTrailingComma(StringBuilder builder, string lineEnding)
    {
        var suffix = "," + lineEnding;
        if (builder.Length >= suffix.Length
            && builder.ToString(builder.Length - suffix.Length, suffix.Length) == suffix)
            builder.Remove(builder.Length - suffix.Length, 1);
    }
}
