using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;

namespace ETL_SQL.Reporting.Authoring;

/// <summary>Generates a new Report-SQL presentation scaffold when no source text exists to patch.</summary>
public sealed class DesignerScriptGenerationService
{
    private const int GridCols = 12;

    public string Generate(DesignerAuthoringState state, string? lineEnding = null)
    {
        var nl = lineEnding ?? Environment.NewLine;
        var sb = new StringBuilder();
        AppendLine(sb, "-- Generated by ETL-SQL Report Designer", nl);
        AppendLine(sb, string.Empty, nl);

        foreach (var parameter in state.Parameters ?? [])
        {
            AppendLine(sb, GenerateParameter(parameter), nl);
            AppendLine(sb, string.Empty, nl);
        }

        if (state.ReportStyle is not null && !string.IsNullOrWhiteSpace(state.ReportStyle.Theme))
        {
            AppendLine(sb, $"SET REPORT THEME = '{EscapeStr(state.ReportStyle.Theme)}';", nl);
            AppendLine(sb, string.Empty, nl);
        }

        foreach (var dataset in state.Datasets ?? [])
        {
            var name = NormalizeDatasetName(dataset.Name);
            var query = string.IsNullOrWhiteSpace(dataset.Query)
                ? "SELECT 1 AS Placeholder"
                : dataset.Query.Trim().TrimEnd(';');
            AppendLine(sb, $"CREATE DATASET {name}{DatasetLifespanClauses(dataset)} AS (", nl);
            AppendLine(sb, $"  {query}", nl);
            AppendLine(sb, ");", nl);
            AppendLine(sb, string.Empty, nl);
        }

        var emitted = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        var pageNumber = 0;
        foreach (var page in state.Pages ?? [])
        {
            pageNumber++;
            var pageName = SanitizeName(string.IsNullOrWhiteSpace(page.Name) ? $"Page{pageNumber}" : page.Name);
            var visuals = page.Visuals ?? [];

            foreach (var visual in visuals)
            {
                var name = SanitizeName(visual.Name, visual.Id);
                if (!emitted.Add(name))
                    continue;
                AppendLine(sb, GenerateElement(visual, visuals, nl, isScaffold: true), nl);
                AppendLine(sb, string.Empty, nl);
            }

            AppendLine(sb, GeneratePage(pageName, page.Mode, visuals, page.PrintLayout, nl), nl);
            AppendLine(sb, string.Empty, nl);
        }

        // Bookmarks come last: they reference pages and named objects, so emitting them after the
        // declarations keeps a generated scaffold readable top to bottom.
        foreach (var bookmark in state.Bookmarks ?? [])
        {
            var text = GenerateBookmark(bookmark, nl);
            if (text.Length == 0) continue;
            AppendLine(sb, text, nl);
            AppendLine(sb, string.Empty, nl);
        }

        return sb.ToString();
    }

    /// <summary>
    /// The dataset's cache rules, written exactly as authored. An absent clause stays absent: a
    /// dataset with no TTL is not the same as one with a zero TTL, and inventing a default here would
    /// silently change how long every report's rows stay valid.
    /// </summary>
    internal static string DatasetLifespanClauses(DesignerAuthoringDataset dataset) =>
        string.IsNullOrWhiteSpace(dataset.Ttl)
            ? string.Empty
            : $" TTL = '{EscapeStr(TrimQuotes(dataset.Ttl))}'";

    /// <summary>Durations round-trip as authored text, which may or may not arrive already quoted.</summary>
    private static string TrimQuotes(string? value) => (value ?? string.Empty).Trim().Trim('\'');

    internal static string GenerateParameter(DesignerAuthoringParameter parameter)
    {
        var name = parameter.Name?.Trim() ?? string.Empty;
        if (!name.StartsWith('@')) name = "@" + name;
        var dataType = string.IsNullOrWhiteSpace(parameter.DataType) ? "VARCHAR" : parameter.DataType.Trim().ToUpperInvariant();
        var initialValue = string.IsNullOrWhiteSpace(parameter.InitialValue) ? string.Empty : $" = {parameter.InitialValue.Trim()}";
        var sensitive = parameter.IsSensitive && dataType is not ("SENSITIVE" or "SECRET" or "ENCRYPTED") ? " PASSWORD" : string.Empty;
        var input = parameter.IsInput ? " INPUT" : string.Empty;
        var output = parameter.IsOutput ? " OUTPUT" : string.Empty;
        var required = parameter.IsRequired ? " REQUIRED" : string.Empty;
        return $"DECLARE {name} {dataType}{initialValue}{sensitive}{input}{output}{required};";
    }

    /// <summary>
    /// Emits one <c>CREATE BOOKMARK</c>. Parameter values are written through verbatim, because the
    /// designer carries them as authored source text — quoting a number here is exactly the bug the
    /// typed bookmark AST exists to prevent.
    /// </summary>
    internal static string GenerateBookmark(DesignerAuthoringBookmark bookmark, string nl)
    {
        var clauses = new List<string>();
        if (!string.IsNullOrWhiteSpace(bookmark.Title))
            clauses.Add($"    TITLE = '{EscapeStr(bookmark.Title!)}'");

        var parameters = (bookmark.Parameters ?? []).Where(p => !string.IsNullOrWhiteSpace(p.Name)).ToList();
        if (parameters.Count > 0)
        {
            var assignments = parameters.Select(p =>
                $"        {(p.Name.StartsWith('@') ? p.Name : "@" + p.Name)} = {p.Value?.Trim()}");
            clauses.Add($"    PARAMETERS ({nl}{string.Join("," + nl, assignments)}{nl}    )");
        }

        if (!string.IsNullOrWhiteSpace(bookmark.Page))
            clauses.Add($"    PAGE = {SanitizeName(bookmark.Page!)}");

        var stateEntries = (bookmark.State ?? []).Where(s => !string.IsNullOrWhiteSpace(s.ObjectName)).ToList();
        if (stateEntries.Count > 0)
        {
            var entries = stateEntries.Select(s =>
                $"        {SanitizeName(s.ObjectName)}.{(s.Property ?? "VISIBLE").ToUpperInvariant()} = {(s.On ? "ON" : "OFF")}");
            clauses.Add($"    STATE ({nl}{string.Join("," + nl, entries)}{nl}    )");
        }

        if (bookmark.IsDefault)
            clauses.Add("    DEFAULT = ON");

        // A bookmark that sets nothing is not a bookmark; emitting an empty body would only produce
        // a script that no longer parses.
        if (clauses.Count == 0) return string.Empty;

        var sb = new StringBuilder();
        AppendLine(sb, $"CREATE BOOKMARK {SanitizeName(bookmark.Name, bookmark.Id)} AS (", nl);
        AppendLine(sb, string.Join("," + nl, clauses), nl);
        sb.Append(");");
        return sb.ToString();
    }

    internal static string GenerateElement(
        DesignerAuthoringVisual visual,
        IReadOnlyList<DesignerAuthoringVisual> allVisuals,
        string nl,
        bool isScaffold = false)
    {
        var sb = new StringBuilder();
        var name = SanitizeName(visual.Name, visual.Id);

        if (string.Equals(visual.Type, "CONTAINER", StringComparison.OrdinalIgnoreCase))
        {
            var containerType = visual.Options.TryGetValue("CONTAINER_TYPE", out var type) ? type : "BOX";
            AppendLine(sb, $"CREATE CONTAINER {name} AS {containerType.ToUpperInvariant()} (", nl);
            if (!string.IsNullOrWhiteSpace(visual.Title))
                AppendLine(sb, $"    TITLE = '{EscapeStr(visual.Title)}',", nl);

            var children = allVisuals.Where(child => child.ContainerId == visual.Id).ToList();
            if (children.Count > 0)
            {
                AppendLine(sb, "    LAYOUT (", nl);
                var slots = children.Select((_, index) => GetSlotLetter(index)).ToList();
                AppendLine(sb, $"        STRUCTURE = '{string.Join(" ", slots)}',", nl);
                AppendLine(sb, "        MAP (", nl);
                for (var index = 0; index < children.Count; index++)
                {
                    var suffix = index < children.Count - 1 ? "," : string.Empty;
                    AppendLine(sb,
                        $"            '{slots[index]}' = {SanitizeName(children[index].Name, children[index].Id)}{suffix}", nl);
                }
                AppendLine(sb, "        )", nl);
                AppendLine(sb, "    )", nl);
            }
            sb.Append(");");
            return sb.ToString();
        }

        if (string.Equals(visual.Type, "BUTTON", StringComparison.OrdinalIgnoreCase))
        {
            var buttonType = visual.Options.TryGetValue("BUTTON_TYPE", out var type) ? type : "REFRESH";
            AppendLine(sb, $"CREATE BUTTON {name} AS (", nl);
            if (!string.IsNullOrWhiteSpace(visual.Title))
                AppendLine(sb, $"    TITLE = '{EscapeStr(visual.Title)}',", nl);
            AppendLine(sb, $"    OPTIONS (BUTTON_TYPE = '{EscapeStr(buttonType)}')", nl);
            sb.Append(");");
            return sb.ToString();
        }

        AppendLine(sb, $"CREATE VISUAL {name} AS {GetVisualTypeKeyword(visual.Type)} (", nl);
        var titleClause = FormatTextClause("TITLE", visual.Formatting?.Title, visual.Title);
        if (titleClause is not null) AppendLine(sb, $"    {titleClause},", nl);
        var subtitleClause = FormatTextClause("SUBTITLE", visual.Formatting?.Subtitle, null);
        if (subtitleClause is not null) AppendLine(sb, $"    {subtitleClause},", nl);

        if (visual.Options.TryGetValue("inline_source", out var inlineSource) && !string.IsNullOrWhiteSpace(inlineSource))
            AppendLine(sb, $"    SOURCE = {inlineSource},", nl);
        else if (!string.IsNullOrWhiteSpace(visual.Dataset))
            AppendLine(sb, $"    SOURCE = {NormalizeDatasetName(visual.Dataset)},", nl);

        // A CUSTOM visual carries its encodings inside CHART; the parser rejects a visual that also
        // declares MAPPINGS. Converting BAR -> CUSTOM used to emit both and produce a script that did
        // not parse, so track whether a CHART clause was written and drop MAPPINGS when one was.
        var emittedChartClause = false;

        if (visual.Options.TryGetValue("advanced_chart", out var advancedChart) && !string.IsNullOrWhiteSpace(advancedChart))
        {
            var chartBlock = advancedChart.Trim().TrimEnd(',');
            if (!chartBlock.StartsWith("CHART", StringComparison.OrdinalIgnoreCase))
                chartBlock = $"CHART ({nl}        {chartBlock}{nl}    )";
            AppendLine(sb, $"    {chartBlock},", nl);
            emittedChartClause = true;
        }
        else if (isScaffold && string.Equals(visual.Type, "CUSTOM", StringComparison.OrdinalIgnoreCase))
        {
            AppendLine(sb, $"    CHART ({nl}        COORDINATE (TYPE = CARTESIAN),{nl}        LAYERS ({nl}            main = RECT ({nl}                ENCODINGS ({nl}                    X = category (TYPE = NOMINAL),{nl}                    Y = value (TYPE = QUANTITATIVE){nl}                ){nl}            ){nl}        ){nl}    ),", nl);
            emittedChartClause = true;
        }

        if (string.Equals(visual.Type, "HTML", StringComparison.OrdinalIgnoreCase) || visual.Options.ContainsKey("html_template"))
        {
            if (visual.Options.TryGetValue("html_mode", out var htmlMode) && string.Equals(htmlMode, "REPEATER", StringComparison.OrdinalIgnoreCase))
                AppendLine(sb, "    MODE = REPEATER,", nl);

            var template = visual.Options.TryGetValue("html_template", out var tmpl) && !string.IsNullOrWhiteSpace(tmpl)
                ? tmpl
                : "<article class=\"custom-card\"><h3>{{Title}}</h3><p>{{Description}}</p></article>";
            AppendLine(sb, $"    TEMPLATE = '{EscapeStr(template)}',", nl);

            if (visual.Options.TryGetValue("html_style", out var htmlStyle) && !string.IsNullOrWhiteSpace(htmlStyle))
                AppendLine(sb, $"    STYLE ( CSS = '{EscapeStr(htmlStyle)}' ),", nl);

            if (visual.Options.TryGetValue("html_fallback", out var fallback) && !string.IsNullOrWhiteSpace(fallback))
                AppendLine(sb, $"    FALLBACK = '{EscapeStr(fallback)}',", nl);
        }

        // Carried verbatim: the parser hands back the authored expression, which may be a literal,
        // a concatenation, or a parameter reference. Re-quoting it would turn an expression into a
        // string.
        if (visual.Options.TryGetValue("text_default", out var textDefault) && !string.IsNullOrWhiteSpace(textDefault))
            AppendLine(sb, $"    DEFAULT = {textDefault.Trim().TrimEnd(',')},", nl);

        var mappings = visual.Mappings
            .Where(mapping => !string.IsNullOrWhiteSpace(mapping.Value))
            .Select(mapping => FormatVisualMapping(visual, mapping.Key, mapping.Value))
            .ToList();
        if (mappings.Count > 0 && !emittedChartClause)
            AppendLine(sb, $"    MAPPINGS ({string.Join(", ", mappings)}),", nl);

        var regularOptions = visual.Options
            .Where(option => !IsReservedOption(option.Key))
            .Select(option => $"{option.Key.ToUpperInvariant()} = {FormatOptionValue(option.Value)}")
            .ToList();
        var dataLabels = FormatDataLabelsOption(visual.Options);
        if (dataLabels is not null) regularOptions.Add(dataLabels);
        var seriesLabels = FormatSeriesLabelsOption(visual.Options);
        if (seriesLabels is not null) regularOptions.Add(seriesLabels);
        var xAxis = FormatAxisOption("X", visual.Formatting?.XAxis);
        if (xAxis is not null) regularOptions.Add(xAxis);
        var yAxis = FormatAxisOption("Y", visual.Formatting?.YAxis);
        if (yAxis is not null) regularOptions.Add(yAxis);
        if (regularOptions.Count > 0)
            AppendLine(sb, $"    OPTIONS ({string.Join(", ", regularOptions)}),", nl);

        var actions = visual.Options
            .Where(option => option.Key.StartsWith("action:", StringComparison.OrdinalIgnoreCase))
            .Select(option => $"{option.Key["action:".Length..].ToUpperInvariant()} = {option.Value}")
            .ToList();
        if (actions.Count > 0)
            AppendLine(sb, $"    ACTIONS ({string.Join(", ", actions)}),", nl);

        var interactions = visual.Options
            .Where(option => option.Key.StartsWith("interaction:", StringComparison.OrdinalIgnoreCase))
            .Select(option => $"{option.Key["interaction:".Length..].ToUpperInvariant()} = {option.Value}")
            .ToList();
        if (interactions.Count > 0)
            AppendLine(sb, $"    INTERACTIONS ({string.Join(", ", interactions)}),", nl);

        if (visual.Options.TryGetValue("cascade", out var cascade) && !string.IsNullOrWhiteSpace(cascade))
            AppendLine(sb, $"    {cascade.Trim().TrimEnd(',')},", nl);

        if (visual.Options.TryGetValue("print_layout", out var printLayout) && !string.IsNullOrWhiteSpace(printLayout))
            AppendLine(sb, $"    {printLayout.Trim().TrimEnd(',')},", nl);

        var styleOptions = new List<string>();
        if (visual.Options.TryGetValue("WIDTH", out var width) && !string.IsNullOrWhiteSpace(width))
            styleOptions.Add($"WIDTH = '{EscapeStr(width)}'");
        if (visual.Options.TryGetValue("HEIGHT", out var height) && !string.IsNullOrWhiteSpace(height))
            styleOptions.Add($"HEIGHT = '{EscapeStr(height)}'");
        if (visual.Options.TryGetValue("BACKGROUND", out var bg) && !string.IsNullOrWhiteSpace(bg))
            styleOptions.Add($"BACKGROUND = '{EscapeStr(bg)}'");
        if (visual.Options.TryGetValue("COLOR", out var color) && !string.IsNullOrWhiteSpace(color))
            styleOptions.Add($"COLOR = '{EscapeStr(color)}'");
        if (visual.Options.TryGetValue("BORDER", out var border) && !string.IsNullOrWhiteSpace(border))
            styleOptions.Add($"BORDER = '{EscapeStr(border)}'");
        if (visual.Options.TryGetValue("BORDER_RADIUS", out var radius) && !string.IsNullOrWhiteSpace(radius))
            styleOptions.Add($"BORDER_RADIUS = '{EscapeStr(radius)}'");
        if (visual.Options.TryGetValue("SHADOW", out var shadow) && !string.IsNullOrWhiteSpace(shadow))
            styleOptions.Add(string.Equals(shadow, "ON", StringComparison.OrdinalIgnoreCase) || string.Equals(shadow, "OFF", StringComparison.OrdinalIgnoreCase)
                ? $"SHADOW = {shadow.ToUpperInvariant()}"
                : $"SHADOW = '{EscapeStr(shadow)}'");
        if (visual.Options.TryGetValue("FONT", out var font) && !string.IsNullOrWhiteSpace(font))
            styleOptions.Add($"FONT = '{EscapeStr(font)}'");
        if (visual.Options.TryGetValue("FONT_SIZE", out var fontSize) && !string.IsNullOrWhiteSpace(fontSize))
            styleOptions.Add($"FONT_SIZE = '{EscapeStr(fontSize)}'");
        if (visual.Options.TryGetValue("FONT_WEIGHT", out var fontWeight) && !string.IsNullOrWhiteSpace(fontWeight))
            styleOptions.Add($"FONT_WEIGHT = '{EscapeStr(fontWeight)}'");
        if (visual.Options.TryGetValue("OPACITY", out var opacity) && !string.IsNullOrWhiteSpace(opacity))
            styleOptions.Add($"OPACITY = '{EscapeStr(opacity)}'");
        foreach (var assignment in visual.Options
                     .Where(option => option.Key.StartsWith("COLOR:", StringComparison.OrdinalIgnoreCase)
                         && !string.IsNullOrWhiteSpace(option.Key["COLOR:".Length..])
                         && !string.IsNullOrWhiteSpace(option.Value)))
            styleOptions.Add($"COLOR:{assignment.Key["COLOR:".Length..]} = '{EscapeStr(assignment.Value)}'");
        if (visual.Formatting?.Palette is { Count: > 0 } palette)
            styleOptions.Add($"PALETTE = ({string.Join(", ", palette.Select(color => $"'{EscapeStr(color)}'"))})");
        if (styleOptions.Count > 0)
            AppendLine(sb, $"    STYLE ({string.Join(", ", styleOptions)}),", nl);

        if (visual.Formatting?.ConditionalRules is { Count: > 0 } rules)
        {
            var formattedRules = rules
                .Where(rule => !string.IsNullOrWhiteSpace(rule.Condition) && !string.IsNullOrWhiteSpace(rule.BackgroundColor))
                .Select(rule =>
                    $"WHEN {rule.Condition.Trim()} THEN '{EscapeStr(rule.BackgroundColor)}'"
                    + (string.IsNullOrWhiteSpace(rule.FontColor)
                        ? string.Empty
                        : $" FONT_COLOR '{EscapeStr(rule.FontColor)}'"))
                .ToList();
            if (formattedRules.Count > 0)
                AppendLine(sb, $"    FORMATTING ({string.Join(", ", formattedRules)}),", nl);
        }

        if (visual.Options.TryGetValue("overlays", out var overlays) && !string.IsNullOrWhiteSpace(overlays))
            AppendLine(sb, $"    {overlays.Trim().TrimEnd(',')},", nl);

        TrimTrailingComma(sb, nl);
        sb.Append(");");
        return sb.ToString();
    }

    internal static string GeneratePage(
        string pageName,
        string mode,
        IReadOnlyList<DesignerAuthoringVisual> visuals,
        DesignerAuthoringPageLayout? printLayout,
        string nl)
    {
        var modeKeyword = string.Equals(mode, "Paginated", StringComparison.OrdinalIgnoreCase)
            ? "PAGINATED"
            : "DASHBOARD";
        if (visuals.Count == 0 && printLayout is null)
            return $"CREATE PAGE [{pageName}] AS {modeKeyword} ( LAYOUT ( STRUCTURE = '.' ) );";

        var sb = new StringBuilder();
        AppendLine(sb, $"CREATE PAGE [{pageName}] AS {modeKeyword} (", nl);
        AppendLine(sb, "    LAYOUT (", nl);
        // A page with no visuals has nothing to map. Emitting an empty MAP () is not just noise: the
        // patcher copies desired clauses into the author's statement one by one, so it would write a
        // meaningless empty clause into a page that never had one.
        if (visuals.Count == 0)
        {
            AppendLine(sb, $"        STRUCTURE = '{EscapeStr(BuildStructure(visuals))}'", nl);
        }
        else
        {
            AppendLine(sb, $"        STRUCTURE = '{EscapeStr(BuildStructure(visuals))}',", nl);
            AppendLine(sb, "        MAP (", nl);
            for (var index = 0; index < visuals.Count; index++)
            {
                var suffix = index < visuals.Count - 1 ? "," : string.Empty;
                AppendLine(sb,
                    $"            '{GetSlotLetter(index)}' = {SanitizeName(visuals[index].Name, visuals[index].Id)}{suffix}", nl);
            }
            AppendLine(sb, "        )", nl);
        }
        AppendLine(sb, printLayout is null ? "    )" : "    ),", nl);
        if (printLayout is not null)
        {
            var options = new List<string>();
            if (!string.IsNullOrWhiteSpace(printLayout.PageSize)) options.Add($"PAGE_SIZE = '{EscapeStr(printLayout.PageSize)}'");
            if (!string.IsNullOrWhiteSpace(printLayout.Orientation)) options.Add($"ORIENTATION = '{EscapeStr(printLayout.Orientation)}'");
            if (printLayout.CustomWidth.HasValue) options.Add($"CUSTOM_WIDTH = {printLayout.CustomWidth.Value}");
            if (printLayout.CustomHeight.HasValue) options.Add($"CUSTOM_HEIGHT = {printLayout.CustomHeight.Value}");
            if (printLayout.MarginTop.HasValue && printLayout.MarginRight.HasValue && printLayout.MarginBottom.HasValue && printLayout.MarginLeft.HasValue)
                options.Add($"MARGINS = ({printLayout.MarginTop.Value}, {printLayout.MarginRight.Value}, {printLayout.MarginBottom.Value}, {printLayout.MarginLeft.Value})");
            if (!string.IsNullOrWhiteSpace(printLayout.Units)) options.Add($"UNITS = '{EscapeStr(printLayout.Units)}'");
            if (!string.IsNullOrWhiteSpace(printLayout.Overflow)) options.Add($"OVERFLOW = '{EscapeStr(printLayout.Overflow)}'");
            AppendLine(sb, $"    PRINT_LAYOUT ({string.Join(", ", options)})", nl);
        }
        sb.Append(");");
        return sb.ToString();
    }

    internal static List<string> BuildReportStyleOptions(DesignerAuthoringReportStyle style)
    {
        var options = new List<string>();
        if (!string.IsNullOrWhiteSpace(style.Theme)) options.Add($"THEME = '{EscapeStr(style.Theme)}'");
        if (!string.IsNullOrWhiteSpace(style.Accent)) options.Add($"ACCENT = '{EscapeStr(style.Accent)}'");
        if (!string.IsNullOrWhiteSpace(style.Background)) options.Add($"BACKGROUND = '{EscapeStr(style.Background)}'");
        if (!string.IsNullOrWhiteSpace(style.Surface)) options.Add($"SURFACE = '{EscapeStr(style.Surface)}'");
        if (!string.IsNullOrWhiteSpace(style.Text)) options.Add($"TEXT = '{EscapeStr(style.Text)}'");
        return options;
    }

    internal static string BuildStructure(IReadOnlyList<DesignerAuthoringVisual> visuals)
    {
        if (visuals.Count == 0) return ".";
        var maxRow = visuals.Max(visual => visual.GridRow + visual.GridRowSpan - 1);
        var usedColumns = Math.Min(GridCols, visuals.Max(visual => visual.GridCol + visual.GridColSpan - 1));
        var grid = new string[maxRow, usedColumns];
        for (var row = 0; row < maxRow; row++)
            for (var column = 0; column < usedColumns; column++)
                grid[row, column] = ".";

        for (var index = 0; index < visuals.Count; index++)
        {
            var visual = visuals[index];
            var slot = GetSlotLetter(index);
            for (var row = visual.GridRow - 1; row < visual.GridRow - 1 + visual.GridRowSpan && row < maxRow; row++)
                for (var column = visual.GridCol - 1; column < visual.GridCol - 1 + visual.GridColSpan && column < usedColumns; column++)
                    grid[row, column] = slot;
        }

        var rows = new List<string>(maxRow);
        for (var row = 0; row < maxRow; row++)
        {
            var slots = new List<string>();
            for (var column = 0; column < usedColumns; column++)
                if (slots.Count == 0 || slots[^1] != grid[row, column])
                    slots.Add(grid[row, column]);
            var value = string.Join(" ", slots);
            if (rows.Count == 0 || rows[^1] != value)
                rows.Add(value);
        }
        return string.Join(" / ", rows);
    }

    internal static string GetSlotLetter(int index)
    {
        var result = string.Empty;
        for (var value = index; value >= 0; value = value / 26 - 1)
            result = (char)('A' + value % 26) + result;
        return result;
    }

    internal static string SanitizeName(string? name, string? fallback = null)
    {
        var input = string.IsNullOrWhiteSpace(name) ? fallback : name;
        if (string.IsNullOrWhiteSpace(input)) return "visual1";
        var safe = Regex.Replace(input.Trim(), @"[^a-zA-Z0-9_]", "_");
        return char.IsLetter(safe[0]) ? safe : "v_" + safe;
    }

    internal static string NormalizeDatasetName(string? name)
    {
        var value = (name ?? string.Empty).Trim();
        if (value.StartsWith('&') || value.StartsWith('#')) value = value[1..];
        return "&" + SanitizeName(value);
    }

    internal static string GetVisualTypeKeyword(string? type) => (type ?? string.Empty).ToUpperInvariant() switch
    {
        "HORIZONTALBAR" => "HBAR",
        var value => value
    };

    internal static string EscapeStr(string value) => value.Replace("'", "''");

    private static string? FormatTextClause(
        string keyword,
        DesignerAuthoringTextFormatting? formatting,
        string? fallbackText)
    {
        var text = fallbackText ?? formatting?.Text;
        var hasStyle = formatting is not null &&
            (!string.IsNullOrWhiteSpace(formatting.Color)
             || !string.IsNullOrWhiteSpace(formatting.Font)
             || !string.IsNullOrWhiteSpace(formatting.Size)
             || !string.IsNullOrWhiteSpace(formatting.Weight)
             || !string.IsNullOrWhiteSpace(formatting.Align));
        if (!hasStyle)
            return string.IsNullOrWhiteSpace(text) ? null : $"{keyword} = '{EscapeStr(text)}'";

        var parts = new List<string>();
        if (!string.IsNullOrWhiteSpace(text)) parts.Add($"TEXT = '{EscapeStr(text)}'");
        if (!string.IsNullOrWhiteSpace(formatting!.Color)) parts.Add($"COLOR = '{EscapeStr(formatting.Color)}'");
        if (!string.IsNullOrWhiteSpace(formatting.Font)) parts.Add($"FONT = '{EscapeStr(formatting.Font)}'");
        if (!string.IsNullOrWhiteSpace(formatting.Size)) parts.Add($"SIZE = '{EscapeStr(formatting.Size)}'");
        if (!string.IsNullOrWhiteSpace(formatting.Weight)) parts.Add($"WEIGHT = '{EscapeStr(formatting.Weight)}'");
        if (!string.IsNullOrWhiteSpace(formatting.Align)) parts.Add($"ALIGN = {formatting.Align.ToUpperInvariant()}");
        return $"{keyword} ({string.Join(", ", parts)})";
    }

    private static string FormatVisualMapping(DesignerAuthoringVisual visual, string role, string column)
    {
        if (visual.Formatting?.Fields is null
            || !visual.Formatting.Fields.TryGetValue(role, out var formatting))
            return $"{role.ToUpperInvariant()} = {column}";

        var builder = new StringBuilder(column);
        if (!string.IsNullOrWhiteSpace(formatting.Format))
            builder.Append($" FORMAT '{EscapeStr(formatting.Format)}'");
        if (!string.IsNullOrWhiteSpace(formatting.Align))
            builder.Append($" ALIGN '{EscapeStr(formatting.Align)}'");
        if (formatting.DataBar)
        {
            builder.Append(" DATA_BAR");
            if (!string.IsNullOrWhiteSpace(formatting.DataBarColor))
                builder.Append($" COLOR '{EscapeStr(formatting.DataBarColor)}'");
        }
        if (!string.IsNullOrWhiteSpace(formatting.ColorScaleFrom))
        {
            builder.Append($" COLOR_SCALE FROM '{EscapeStr(formatting.ColorScaleFrom)}'");
            if (!string.IsNullOrWhiteSpace(formatting.ColorScaleTo))
                builder.Append($" TO '{EscapeStr(formatting.ColorScaleTo)}'");
        }
        if (!string.IsNullOrWhiteSpace(formatting.DisplayName))
            builder.Append($" AS '{EscapeStr(formatting.DisplayName)}'");
        return builder.ToString();
    }

    private static string? FormatAxisOption(
        string axis,
        Dictionary<string, string>? options)
    {
        if (options is not { Count: > 0 }) return null;
        var body = options
            .Where(option => !string.IsNullOrWhiteSpace(option.Value))
            .Select(option => $"{option.Key.ToUpperInvariant()} = {FormatOptionValue(option.Value)}")
            .ToList();
        return body.Count > 0 ? $"{axis}_AXIS ({string.Join(", ", body)})" : null;
    }

    private static string FormatOptionValue(string value)
    {
        var trimmed = value.Trim();
        if (decimal.TryParse(trimmed, System.Globalization.NumberStyles.Number,
                System.Globalization.CultureInfo.InvariantCulture, out _)
            || trimmed.Equals("ON", StringComparison.OrdinalIgnoreCase)
            || trimmed.Equals("OFF", StringComparison.OrdinalIgnoreCase)
            || trimmed.Equals("TRUE", StringComparison.OrdinalIgnoreCase)
            || trimmed.Equals("FALSE", StringComparison.OrdinalIgnoreCase))
            return trimmed.ToUpperInvariant();
        return $"'{EscapeStr(value)}'";
    }

    private static string FormatStructuredOptionValue(string value)
    {
        var upper = value.Trim().ToUpperInvariant();
        return upper is "ON" or "OFF" or "TRUE" or "FALSE" or "START" or "END" or "SOLID" or "DASHED"
            ? upper
            : FormatOptionValue(value);
    }

    private static string? FormatDataLabelsOption(IReadOnlyDictionary<string, string> options)
    {
        if (!options.TryGetValue("DATA_LABELS", out var enabled)) return null;
        var details = options
            .Where(option => option.Key.StartsWith("DATA_LABELS:", StringComparison.OrdinalIgnoreCase)
                && !option.Key.Equals("DATA_LABELS:LEADER_LINE", StringComparison.OrdinalIgnoreCase)
                && !option.Key.StartsWith("DATA_LABELS:LEADER_LINE:", StringComparison.OrdinalIgnoreCase)
                && !string.IsNullOrWhiteSpace(option.Value))
            .Select(option => $"{option.Key["DATA_LABELS:".Length..].ToUpperInvariant()} = {FormatOptionValue(option.Value)}")
            .ToList();

        if (options.TryGetValue("DATA_LABELS:LEADER_LINE", out var leaderEnabled))
        {
            var leaderDetails = options
                .Where(option => option.Key.StartsWith("DATA_LABELS:LEADER_LINE:", StringComparison.OrdinalIgnoreCase)
                    && !string.IsNullOrWhiteSpace(option.Value))
                .Select(option => $"{option.Key["DATA_LABELS:LEADER_LINE:".Length..].ToUpperInvariant()} = {FormatStructuredOptionValue(option.Value)}")
                .ToList();
            var leaderText = $"LEADER_LINE = {FormatStructuredOptionValue(leaderEnabled)}";
            if (leaderDetails.Count > 0) leaderText += $" WITH ({string.Join(", ", leaderDetails)})";
            details.Add(leaderText);
        }

        var value = FormatOptionValue(enabled);
        return details.Count == 0 ? $"DATA_LABELS = {value}" : $"DATA_LABELS = {value} WITH ({string.Join(", ", details)})";
    }

    private static string? FormatSeriesLabelsOption(IReadOnlyDictionary<string, string> options)
    {
        if (!options.TryGetValue("SERIES_LABELS", out var enabled)) return null;
        var details = options
            .Where(option => option.Key.StartsWith("SERIES_LABELS:", StringComparison.OrdinalIgnoreCase)
                && !string.IsNullOrWhiteSpace(option.Value))
            .Select(option => $"{option.Key["SERIES_LABELS:".Length..].ToUpperInvariant()} = {FormatStructuredOptionValue(option.Value)}")
            .ToList();
        var value = FormatStructuredOptionValue(enabled);
        return details.Count == 0 ? $"SERIES_LABELS = {value}" : $"SERIES_LABELS = {value} WITH ({string.Join(", ", details)})";
    }

    private static bool IsReservedOption(string key) =>
        string.Equals(key, "WIDTH", StringComparison.OrdinalIgnoreCase)
        || string.Equals(key, "HEIGHT", StringComparison.OrdinalIgnoreCase)
        || string.Equals(key, "BACKGROUND", StringComparison.OrdinalIgnoreCase)
        || string.Equals(key, "COLOR", StringComparison.OrdinalIgnoreCase)
        || string.Equals(key, "BORDER", StringComparison.OrdinalIgnoreCase)
        || string.Equals(key, "BORDER_RADIUS", StringComparison.OrdinalIgnoreCase)
        || string.Equals(key, "SHADOW", StringComparison.OrdinalIgnoreCase)
        || string.Equals(key, "FONT", StringComparison.OrdinalIgnoreCase)
        || string.Equals(key, "FONT_SIZE", StringComparison.OrdinalIgnoreCase)
        || string.Equals(key, "FONT_WEIGHT", StringComparison.OrdinalIgnoreCase)
        || string.Equals(key, "OPACITY", StringComparison.OrdinalIgnoreCase)
        || string.Equals(key, "DATA_LABELS", StringComparison.OrdinalIgnoreCase)
        || key.StartsWith("DATA_LABELS:", StringComparison.OrdinalIgnoreCase)
        || string.Equals(key, "SERIES_LABELS", StringComparison.OrdinalIgnoreCase)
        || key.StartsWith("SERIES_LABELS:", StringComparison.OrdinalIgnoreCase)
        || key.StartsWith("COLOR:", StringComparison.OrdinalIgnoreCase)
        || string.Equals(key, "overlays", StringComparison.OrdinalIgnoreCase)
        || string.Equals(key, "CONTAINER_TYPE", StringComparison.OrdinalIgnoreCase)
        || string.Equals(key, "BUTTON_TYPE", StringComparison.OrdinalIgnoreCase)
        || string.Equals(key, "inline_source", StringComparison.OrdinalIgnoreCase)
        || string.Equals(key, "cascade", StringComparison.OrdinalIgnoreCase)
        || string.Equals(key, "text_default", StringComparison.OrdinalIgnoreCase)
        || string.Equals(key, "print_layout", StringComparison.OrdinalIgnoreCase)
        || string.Equals(key, "advanced_chart", StringComparison.OrdinalIgnoreCase)
        || string.Equals(key, "html_template", StringComparison.OrdinalIgnoreCase)
        || string.Equals(key, "html_mode", StringComparison.OrdinalIgnoreCase)
        || string.Equals(key, "html_style", StringComparison.OrdinalIgnoreCase)
        || string.Equals(key, "html_fallback", StringComparison.OrdinalIgnoreCase)
        || key.StartsWith("action:", StringComparison.OrdinalIgnoreCase)
        || key.StartsWith("interaction:", StringComparison.OrdinalIgnoreCase);

    private static void AppendLine(StringBuilder builder, string value, string lineEnding) =>
        builder.Append(value).Append(lineEnding);

    private static void TrimTrailingComma(StringBuilder builder, string lineEnding)
    {
        var suffix = "," + lineEnding;
        if (builder.Length >= suffix.Length
            && builder.ToString(builder.Length - suffix.Length, suffix.Length) == suffix)
            builder.Remove(builder.Length - suffix.Length, 1);
    }
}
