<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\ETL-SQL.Analysis\ETL-SQL.Analysis.csproj" />
    <ProjectReference Include="..\..\src\ETL-SQL.Core\ETL-SQL.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>ETL_SQL.LintTests</RootNamespace>
    <AssemblyName>ETL-SQL.LintTests</AssemblyName>
  </PropertyGroup>

</Project>
