namespace ETL_SQL.Core.Parser
{
    public enum TokenType
    {
        // Keywords
        CREATE, CONNECTION, ON, FILE, DATABASE, EXCEL, JSON, XML,
        MSSQL, ORACLE, POSTGRES, MOCKDB, ODBC, FLATFILE, GENERATE,
        SELECT, FROM, WHERE, GROUP, BY, HAVING,
        INSERT, INTO, VALUES,
        UPDATE, SET,
        DELETE, TRUNCATE, PIVOT, UNPIVOT, MERGE, USING, MATCHED, SOURCE,
        COPY, MOVE, COMPRESS, SEND, RECEIVE, EMAIL, ADD, COLUMN,
        DOCKER, CLOSE,
        DECLARE,
        AND, OR, NOT, AS, IS,
        IN, LIKE, ESCAPE,
        CASE, WHEN, THEN, ELSE, END,
        TABLE, IF, EXISTS, IDENTITY, DEFAULT, DROP, WITH, WITHIN,
        DISTINCT, TOP, PERCENT, TIES, LIMIT, OFFSET, ROWS, ROW,
        BEGIN, WHILE, FOR, FOREACH, EACH, TO, STEP, ZONE, TIME,
        TRY, CATCH, THROW,
        PRINT, RAISEERROR, ASSERT, EXEC, EXECUTE,
        RETURN, BREAK, CONTINUE,
        PATH, ROOT, AUTO, RAW, EXPLICIT, ELEMENTS, INDEX, UNIQUE, EXPLAIN, SEMI, ANTI, PROCEDURE, FUNCTION, RETURNS, REQUIRE,
        PRIMARY, KEY, FOREIGN, CHECK, REFERENCES, CONSTRAINT, CLEAR, SESSION, SESSIONS,
        TRANSACTION, TRAN, COMMIT, ROLLBACK, ALTER, AT, RECURSIVE,
        DIRECTORY, RENAME, ENCRYPT, DECRYPT, DIRECTORY_CONTENTS,
        COPY_FILE, MOVE_FILE, RENAME_FILE, DELETE_FILE, COMPRESS_FILE, ENCRYPT_FILE, DECRYPT_FILE,
        CREATE_DIRECTORY, DELETE_DIRECTORY, RENAME_DIRECTORY, MOVE_DIRECTORY,
        COPY_DIRECTORY, DELETE_DIRECTORY_CONTENTS,
        COMPRESS_DIRECTORY, ENCRYPT_DIRECTORY, DECRYPT_DIRECTORY,
        SEND_FILE, RECEIVE_FILE, FILE_SEND, FILE_RECEIVE, SFTP, FTP_CONN, AZURE_BLOB,
        DATETIMEFROMPARTS, TIMEFROMPARTS, DATETIMEOFFSETSFROMPARTS, HASHBYTES, NEWID, NEWSEQUENTIALID, CHECKSUM, BINARY_CHECKSUM,
        STUFF, STRING_ESCAPE, STRING_SPLIT, ASCII, UNICODE, CHAR, PATINDEX, STR, QUOTENAME, TRANSLATE, DATALENGTH, TO_STR, REPLICATE, TRY_CAST,
        SIN, COS, TAN, ASIN, ACOS, ATAN, ATAN2, SIGN,
        WAIT, WAITFOR, DELAY,
        HELP, TYPE, TARGET, TRUE, FALSE,
        PASSWORD, SHOW_PASSWORD, OUTPUT, INPUT, PARALLEL, RUN, SCRIPT, USE, START, STOP, PAUSE, OFF, PROFILE, PROFILING, SHOW, VERSION, KILL,
        BULK, LOAD, BATCHSIZE, MAXERRORS, FIELDTERMINATOR, ROWTERMINATOR, FIRSTROW, DATA_SOURCE,
        NULL, YEAR, MONTH, DAY, HOUR, MINUTE, SECOND, INCLUDE_NULL_VALUES, WITHOUT_ARRAY_WRAPPER,
        JOIN_SPILL_THRESHOLD, EXTERNAL_HASH_PARTITIONS, EXTERNAL_SORT_CHUNK_SIZE, WINDOW_SPILL_THRESHOLD, TEMP_TABLE_SPILL_THRESHOLD,
        MAX_RECURSIVE_DEPTH, MAX_IN_MEMORY_BATCHES, FOREACH_PAGE_SIZE, MAX_MESSAGES, MAX_FILE_OPERATIONS,
        MAX_PARALLEL_DEGREE, MAX_STRING_RESULT_SIZE, REGEX_MATCH_TIMEOUT, MAX_LAST_RESULT_ROWS, MAX_GENERATE_ROWS,
        SPILL_ENCRYPTION, SPILL_COMPRESSION,
        MAX_GROUPING_SETS, SET_CUBE_LIMIT,
        MAX_SESSION_SIZE,
        TELEMETRY,
        LINEAGE, SEND_EMAIL, SUBJECT, BODY, ATTACH, CC, BCC,
        JOB, SCHEDULE, EVERY, HISTORY, JOBS, LINT, SSH_KEY_PAIR, WHAT_IF, SYSDATE,
        CONNECTIONS, TABLES, COLUMNS, TAGS, TAG, VALUE, BITS, ALGORITHM, PASSPHRASE, COMMENT,
        SUBSTRING, POSITION, OVERLAY, EXTRACT, TRIM, PLACING, LEADING, TRAILING, BOTH,
        CHARACTER_LENGTH, CHAR_LENGTH, OCTET_LENGTH,
        VARIABLES, LOCAL, ANALYZE, SAFE, ZONES,
        SETS, BANG,     // SETS keyword and ! prefix for set names
        ROLLUP, CUBE, GROUPING,   // GROUP BY extensions
        RANGE, BETWEEN, PRECEDING, FOLLOWING, UNBOUNDED, CURRENT,
        UNTIL,
        LF, CR, CRLF, TAB,
        
        // Joins
        JOIN, INNER, LEFT, RIGHT, OUTER, FULL, CROSS, APPLY, HASH, LOOP,
        
        // Set Operations
        UNION, ALL, EXCEPT, INTERSECT,
 
        // Functions
        UPPER, LOWER, CONCAT, CAST, TRUNC, GETDATE,
        CURRENT_TIMESTAMP, CURRENT_DATE, CURRENT_TIME, FORMAT,
        OVER, PARTITION, ORDER, ASC, DESC,
        SUM, AVG, COUNT, MIN, MAX,
        SEQUENCE, RANDOM, RANDOM_INT, RANDOM_DECIMAL,
 
        // Data types
        INT, INTEGER, BIGINT, SMALLINT, TINYINT, BIT, BOOLEAN, BOOL,
        DECIMAL, NUMERIC, MONEY, SMALLMONEY, FLOAT, REAL, DOUBLE,
        DATE, DATETIME2, SMALLDATETIME, DATETIMEOFFSET, TIMESTAMP,
        VARCHAR, VARCHAR2, NCHAR, NVARCHAR, TEXT, NTEXT, BINARY, VARBINARY, IMAGE, STRING,
        MINMAX, SENSITIVE, SECRET,
        UNIQUEIDENTIFIER, UUID, GUID, GEOMETRY, GEOGRAPHY, HIERARCHYID,
        VARIANT, SQL_VARIANT, ANY, MARKDOWN,

        IDENTIFIER,
        VARIABLE,   // @variableName
        STRING_LITERAL,
        NUMBER,
        DATETIME,   // Common parsed date types
 
        // Symbols / Operators
        STAR,       // *
        COMMA,      // ,
        SEMICOLON,  // ;
        DOT,        // .
        LPAREN,     // (
        RPAREN,     // )
        LBRACKET,   // [
        RBRACKET,   // ]
        EQUALS,     // =
        LESS_THAN,  // <
        GREATER_THAN, // >
        LESS_EQUALS, // <=
        GREATER_EQUALS, // >=
        NOT_EQUALS, // != or <>
 
        PLUS,       // +
        MINUS,      // -
        SLASH,      // /
        MODULO,     // %
        QUESTION,   // ?
        PARAMETER,  // ? or ?n
        COLUMN_TAG, // /*@d: ... */

        // ── Report-SQL tokens (Phase 9A) ───────────────────────────────────
        // All are non-reserved: only treated as keywords inside CREATE VISUAL /
        // CREATE DASHBOARD / CREATE PAGE context.
        VISUAL, DASHBOARD, THEME, LAYOUT, REFRESH,
        BAR, LINE, PIE, GAUGE, RADAR, SCATTER, HEATMAP, TABLE_VISUAL, FUNNEL, WATERFALL, FORMATTING,
        DONUT, HBAR, BOXPLOT, TREEMAP, COLORS,
        BOTTOM,  // position keyword (TOP/LEFT/RIGHT already registered via LanguageMetadata)
        TITLE, SUBTITLE, DESCRIPTION,
        MAPPINGS, OPTIONS, ACTIONS, STRUCTURE, MAP, SERIES,
        SLICER, CARD, ON_CLICK, DRILL_DOWN, SET_PARAMETER, ON_CHANGE,
        TTL, KEYFILE, X_AXIS, Y_AXIS,
        PAGE, PAGES, DATASET,
        REPORT,
        STYLE, CONTAINER, BOX, SCROLL, NAVIGATION, COMBO, NAV_TAB, BUTTON, LINK_NAV,
        DATEPICKER, SLIDER, MULTISELECT, SEARCH,
        TOOLTIP, BACK,
        TEMPLATE, TEMPLATE_PATH,
        SUMMARY, GRAND_TOTAL, GRAND_TOTAL_ROW, GRAND_TOTAL_COLUMN, SUMMARIZE_ROW, SUMMARIZE_COLUMN,
        GRID, NONE, HEADER, FOOTER, DATA_LABELS, DATA_LABELS_POSITION, FONT_FAMILY, FONT_WEIGHT,
        FONT_SIZE, CENTER, INSIDE, INSIDE_TOP, INSIDE_BOTTOM, INSIDE_LEFT, INSIDE_RIGHT,
        INSIDE_TOP_LEFT, INSIDE_TOP_RIGHT, INSIDE_BOTTOM_LEFT, INSIDE_BOTTOM_RIGHT,
        GAUGE_STYLE, SHOW_NO_DATA_PLACEHOLDER,
        CSS, JS, FAVICON, LOGO, BACKGROUND, NAV_OVERRIDE, HEAD,

        EXPECT, SCHEMA,   // EXPECT SCHEMA statement

        // ── Overlay tokens (Phase 9F) ──────────────────────────────────────
        OVERLAYS, GOAL, AVERAGE, MOVING_AVG, LINEAR, EXPONENTIAL, LOGARITHMIC, POLYNOMIAL, POWER,
        SOLID, DASHED, DOTTED, COLOR,

        EOF         // End of file / string
    }
}
