namespace ETL_SQL.Core.Parser
{
    public enum TokenType
    {
        // Keywords
        CREATE, CONNECTION, ON, FILE, DATABASE, EXCEL, JSON, XML,
        MSSQL, ORACLE, POSTGRES, MOCKDB, ODBC, FLATFILE,
        SELECT, FROM, WHERE, GROUP, BY, HAVING,
        INSERT, INTO, VALUES,
        UPDATE, SET,
        DELETE, TRUNCATE, PIVOT, UNPIVOT, MERGE, USING, MATCHED, SOURCE,
        COPY, MOVE, COMPRESS, SEND, ADD, COLUMN,
        DOCKER, CLOSE, START_DOCKER, STOP_DOCKER, PAUSE_DOCKER, CLOSE_DOCKER,
        DECLARE,
        AND, OR, NOT, AS, IS,
        IN, LIKE,
        CASE, WHEN, THEN, ELSE, END,
        TABLE, IF, EXISTS, IDENTITY, DEFAULT, DROP, WITH, WITHIN,
        DISTINCT, TOP, LIMIT, OFFSET, ROWS, ROW,
        BEGIN, WHILE, FOR, FOREACH, EACH, TO, STEP, ZONE, TIME,
        TRY, CATCH, THROW,
        PRINT, RAISEERROR, EXEC, EXECUTE,
        RETURN, BREAK, CONTINUE,
        PATH, ROOT, AUTO, RAW, EXPLICIT, ELEMENTS, INDEX, UNIQUE, EXPLAIN, SEMI, ANTI, PROCEDURE, FUNCTION, RETURNS,
        PRIMARY, KEY, FOREIGN, CHECK, REFERENCES, CONSTRAINT,
        TRANSACTION, TRAN, COMMIT, ROLLBACK, ALTER, AT, RECURSIVE,
        DIRECTORY, RENAME,
        COPY_FILE, MOVE_FILE, RENAME_FILE, DELETE_FILE, COMPRESS_FILE, ENCRYPT_FILE, DECRYPT_FILE,
        CREATE_DIRECTORY, DELETE_DIRECTORY, RENAME_DIRECTORY, MOVE_DIRECTORY,
        COPY_DIRECTORY, DELETE_DIRECTORY_CONTENTS,
        SEND_FILE, RECEIVE_FILE, SFTP, FTP_CONN, AZURE_BLOB,
        DATETIMEFROMPARTS, TIMEFROMPARTS, DATETIMEOFFSETSFROMPARTS, HASHBYTES, NEWID, NEWSEQUENTIALID, CHECKSUM, BINARY_CHECKSUM,
        STUFF, STRING_ESCAPE, STRING_SPLIT, ASCII, UNICODE, CHAR, PATINDEX, STR, QUOTENAME, TRANSLATE, DATALENGTH, TO_STR, REPLICATE, TRY_CAST,
        SIN, COS, TAN, ASIN, ACOS, ATAN, ATAN2, SIGN,
        WAITFOR, DELAY,
        HELP, TYPE, TARGET, TRUE, FALSE,
        PASSWORD, OUTPUT, INPUT, PARALLEL, RUN, SCRIPT, USE, START, STOP, PAUSE, OFF, PROFILE, PROFILING, SHOW,
        BULK, LOAD, BATCHSIZE, MAXERRORS, FIELDTERMINATOR, ROWTERMINATOR, FIRSTROW, DATA_SOURCE,
        NULL, YEAR, MONTH, DAY, HOUR, MINUTE, SECOND, INCLUDE_NULL_VALUES, WITHOUT_ARRAY_WRAPPER,
        LINEAGE, SEND_EMAIL, SUBJECT, BODY, ATTACH, CC, BCC,
        JOB, SCHEDULE, EVERY, HISTORY, JOBS, LINT,
        SETS, BANG,     // SETS keyword and ! prefix for set names
        RANGE, BETWEEN, PRECEDING, FOLLOWING, UNBOUNDED, CURRENT,
        
        // Joins
        JOIN, INNER, LEFT, RIGHT, OUTER, FULL, CROSS, APPLY, HASH, LOOP,
        
        // Set Operations
        UNION, ALL, EXCEPT, INTERSECT,
 
        // Functions
        UPPER, LOWER, CONCAT, CAST,
        CURRENT_TIMESTAMP, CURRENT_DATE, CURRENT_TIME, FORMAT,
        OVER, PARTITION, ORDER, ASC, DESC,
 
        // Data types
        INT, INTEGER, BIGINT, SMALLINT, TINYINT, BIT, BOOLEAN, BOOL,
        DECIMAL, NUMERIC, MONEY, SMALLMONEY, FLOAT, REAL, DOUBLE,
        DATE, DATETIME2, SMALLDATETIME, DATETIMEOFFSET, TIMESTAMP,
        VARCHAR, VARCHAR2, NCHAR, NVARCHAR, TEXT, NTEXT, BINARY, VARBINARY, IMAGE,
        UNIQUEIDENTIFIER, UUID, GUID, GEOMETRY, GEOGRAPHY, HIERARCHYID,
        VARIANT, SQL_VARIANT, ANY,

        IDENTIFIER,
        VARIABLE,   // @variableName
        STRING,
        NUMBER,
        DATETIME,   // Common parsed date types
 
        // Symbols / Operators
        STAR,       // *
        COMMA,      // ,
        SEMICOLON,  // ;
        DOT,        // .
        LPAREN,     // (
        RPAREN,     // )
        LBRACKET,   // [
        RBRACKET,   // ]
        EQUALS,     // =
        LESS_THAN,  // <
        GREATER_THAN, // >
        LESS_EQUALS, // <=
        GREATER_EQUALS, // >=
        NOT_EQUALS, // != or <>
 
        PLUS,       // +
        MINUS,      // -
        SLASH,      // /
        MODULO,     // %
        QUESTION,   // ?
        COLUMN_TAG, // /*@d: ... */
        
        EOF         // End of file / string
    }
}
