<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>ETL_SQL.Core</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Docker.DotNet.Enhanced" />
    <PackageReference Include="Microsoft.Extensions.Configuration" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="PgpCore" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="Serilog.Extensions.Logging" />
    <PackageReference Include="Serilog.Sinks.File" />
    <PackageReference Include="System.Linq.Async" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" />
    <PackageReference Include="Testcontainers" />
    <PackageReference Include="Testcontainers.MsSql" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="Testcontainers.Oracle" />
    <PackageReference Include="Testcontainers.MySql" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ETL-SQL.Tests, PublicKey=$(AssemblyPublicKey)" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\Help\**\*.md" />
  </ItemGroup>

</Project>
