<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>ETL_SQL.Connectors</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentFTP" />
    <PackageReference Include="Microsoft.Data.SqlClient" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="MongoDB.Driver" />
    <PackageReference Include="MySqlConnector" />
    <PackageReference Include="Neo4j.Driver" />
    <PackageReference Include="Npgsql" />
    <PackageReference Include="Oracle.ManagedDataAccess.Core" />
    <PackageReference Include="Polly" />
    <PackageReference Include="Google.Cloud.BigQuery.V2" />
    <PackageReference Include="Snowflake.Data" />
    <PackageReference Include="SSH.NET" />
    <PackageReference Include="System.Data.Odbc" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ETL-SQL.Connectors.Common\ETL-SQL.Connectors.Common.csproj" />
    <ProjectReference Include="..\ETL-SQL.Core\ETL-SQL.Core.csproj" />
    <ProjectReference Include="..\ETL-SQL.Engine\ETL-SQL.Engine.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ETL-SQL.Tests, PublicKey=$(AssemblyPublicKey)" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="ETL_SQL.Core" />
    <Using Include="ETL_SQL.Core.Parser" />
    <Using Include="ETL_SQL.Engine" />
  </ItemGroup>

</Project>
