using System.Text;

namespace ETL_SQL.ReportPortal.Services;

/// <summary>
/// Composes the persisted Orchestrator job script for a subscription. The script is a
/// credential-free trigger only (the dataset-refresh precedent): export and email delivery
/// run inside the portal after delivery-time reauthorization, so no SMTP credential,
/// recipient list, or report parameter is ever written to disk.
/// </summary>
public static class SubscriptionTriggerScript
{
    public static string Compose(int subscriptionId)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"-- Subscription {subscriptionId} delivery trigger");
        sb.AppendLine("-- Generated by ETL-SQL Portal - do not edit manually.");
        sb.AppendLine("-- Export and email delivery run inside the portal after delivery-time");
        sb.AppendLine("-- reauthorization; this scheduled script intentionally contains no");
        sb.AppendLine("-- credentials, recipients, or report parameters.");
        sb.AppendLine($"PRINT 'Portal subscription delivery trigger for subscription {subscriptionId}';");
        return sb.ToString();
    }

    /// <summary>
    /// Atomically writes the trigger script (P1.2): the content lands in a unique temp file in
    /// the same directory and is moved over the destination, so a crash mid-write can never
    /// leave a truncated script and concurrent readers always see a complete file.
    /// </summary>
    public static void Write(string path, int subscriptionId)
    {
        var tmp = path + $".tmp-{Guid.NewGuid():N}";
        File.WriteAllText(tmp, Compose(subscriptionId));
        File.Move(tmp, path, overwrite: true);
    }
}
