using System.Text;

namespace ETL_SQL.ReportPortal.Services;

/// <summary>
/// Composes the persisted Orchestrator job script for a subscription. The script is a
/// credential-free trigger only (the dataset-refresh precedent): export and email delivery
/// run inside the portal after delivery-time reauthorization, so no SMTP credential,
/// recipient list, or report parameter is ever written to disk.
/// </summary>
public static class SubscriptionTriggerScript
{
    public static string Compose(int subscriptionId)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"-- Subscription {subscriptionId} delivery trigger");
        sb.AppendLine("-- Generated by ETL-SQL Report Portal - do not edit manually.");
        sb.AppendLine("-- Export and email delivery run inside the portal after delivery-time");
        sb.AppendLine("-- reauthorization; this scheduled script intentionally contains no");
        sb.AppendLine("-- credentials, recipients, or report parameters.");
        sb.AppendLine($"PRINT 'Portal subscription delivery trigger for subscription {subscriptionId}';");
        return sb.ToString();
    }
}
