<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>ETL_SQL.Benchmarks</RootNamespace>
    <Nullable>enable</Nullable>
    <AssemblyName>ETL-SQL.Benchmarks</AssemblyName>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <StartupObject>ETL_SQL.Benchmarks.Program</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
    <PackageReference Include="Moq" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="Spectre.Console" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\ETL-SQL.App\ETL-SQL.App.csproj" />
    <ProjectReference Include="..\..\src\ETL-SQL.Core\ETL-SQL.Core.csproj" />
    <ProjectReference Include="..\..\src\ETL-SQL.Engine\ETL-SQL.Engine.csproj" />
    <ProjectReference Include="..\..\src\ETL-SQL.Connectors\ETL-SQL.Connectors.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="ETL_SQL.Core" />
    <Using Include="ETL_SQL.Core.Parser" />
    <Using Include="ETL_SQL.Engine" />
    <Using Include="ETL_SQL.Connectors" />
    <Using Include="BenchmarkDotNet.Attributes" />
    <Using Include="BenchmarkDotNet.Running" />
  </ItemGroup>

</Project>
