<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <RootNamespace>ETL_SQL.PerfTests</RootNamespace>
    <Nullable>disable</Nullable>
    <AssemblyName>ETL-SQL.PerfTests</AssemblyName>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Serilog" />
    <PackageReference Include="Serilog.Sinks.File" />
    <PackageReference Include="Serilog.Sinks.XUnit" />
    <PackageReference Include="Spectre.Console" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="coverlet.collector">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\ETL-SQL.App\ETL-SQL.App.csproj" />
    <ProjectReference Include="..\..\src\ETL-SQL.Core\ETL-SQL.Core.csproj" />
    <ProjectReference Include="..\..\src\ETL-SQL.Engine\ETL-SQL.Engine.csproj" />
    <ProjectReference Include="..\..\src\ETL-SQL.Connectors\ETL-SQL.Connectors.csproj" />
    <ProjectReference Include="..\..\src\ETL-SQL.Portal\ETL-SQL.Portal.csproj" />
    <ProjectReference Include="..\..\src\ETL-SQL.Orchestrator\ETL-SQL.Orchestrator.csproj" />
    <ProjectReference Include="..\..\src\ETL-SQL.Gateway\ETL-SQL.Gateway.csproj" />
    <ProjectReference Include="..\..\tests\ETL-SQL.Portal.Tests\ETL-SQL.Portal.Tests.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="ETL_SQL.Core" />
    <Using Include="ETL_SQL.Core.Parser" />
    <Using Include="ETL_SQL.Engine" />
    <Using Include="ETL_SQL.Connectors" />
  </ItemGroup>

</Project>
