<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>ETL_SQL.ReportBuilder</RootNamespace>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ETL-SQL.Core\ETL-SQL.Core.csproj" />
    <ProjectReference Include="..\ETL-SQL.Engine\ETL-SQL.Engine.csproj" />
    <ProjectReference Include="..\ETL-SQL.Connectors\ETL-SQL.Connectors.csproj" />
  </ItemGroup>


</Project>
