<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>ETL_SQL.WorkstationEditor</RootNamespace>
    <AssemblyName>ETL-SQL-Editor</AssemblyName>
    <ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
    <RuntimeIdentifiers>win-x64;linux-x64;osx-arm64</RuntimeIdentifiers>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ETL-SQL.Analysis\ETL-SQL.Analysis.csproj" />
    <ProjectReference Include="..\ETL-SQL.Connectors.Common\ETL-SQL.Connectors.Common.csproj" />
    <ProjectReference Include="..\ETL-SQL.Core\ETL-SQL.Core.csproj" />
    <ProjectReference Include="..\ETL-SQL.Orchestrator\ETL-SQL.Orchestrator.csproj" />
    <ProjectReference Include="..\ETL-SQL.Reporting\ETL-SQL.Reporting.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ETL-SQL.Tests, PublicKey=$(AssemblyPublicKey)" />
  </ItemGroup>

</Project>
