<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>ETL_SQL.Orchestrator</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="Npgsql" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="ETL_SQL.Core" />
    <Using Include="ETL_SQL.Core.Data" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ETL-SQL.Analysis\ETL-SQL.Analysis.csproj" />
    <ProjectReference Include="..\ETL-SQL.Core\ETL-SQL.Core.csproj" />
    <ProjectReference Include="..\ETL-SQL.Infrastructure.Docker\ETL-SQL.Infrastructure.Docker.csproj" />
    <ProjectReference Include="..\ETL-SQL.Infrastructure.Sqlite\ETL-SQL.Infrastructure.Sqlite.csproj" />
    <ProjectReference Include="..\ETL-SQL.Engine\ETL-SQL.Engine.csproj" />
    <ProjectReference Include="..\ETL-SQL.Connectors\ETL-SQL.Connectors.csproj" />
    <ProjectReference Include="..\ETL-SQL.ReportBuilder\ETL-SQL.ReportBuilder.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ETL-SQL.Tests, PublicKey=$(AssemblyPublicKey)" />
  </ItemGroup>

</Project>
