<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>ETL_SQL.Infrastructure.Docker</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Docker.DotNet.Enhanced" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="Testcontainers" />
    <PackageReference Include="Testcontainers.MsSql" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="Testcontainers.Oracle" />
    <PackageReference Include="Testcontainers.MySql" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ETL-SQL.Core\ETL-SQL.Core.csproj" />
  </ItemGroup>

</Project>
