using System;
using System.IO;
using System.Threading.Tasks;
using ETL_SQL.App;
using ETL_SQL.Common;
using ETL_SQL.Core.Data;
using ETL_SQL.Orchestrator.Storage;
using Microsoft.Data.Sqlite;
using Npgsql;
using Testcontainers.PostgreSql;
using Xunit;

namespace ETL_SQL.Tests.Orchestration
{
    /// <summary>
    /// Practical HA P1.3: proves <c>admin migrate-database</c>'s core copies a SQLite database into a
    /// pre-existing PostgreSQL schema, coercing each value to the target column type (bool/timestamp/
    /// numeric/uuid where SQLite stored INTEGER/TEXT), verifying row counts, resyncing identity
    /// sequences, and failing closed on a missing target or a mismatch.
    /// </summary>
    [Trait("Category", "Integration")]
    public sealed class DatabaseMigrationServiceTests : IAsyncLifetime
    {
        private readonly PostgreSqlContainer _pg = new PostgreSqlBuilder("postgres:16-alpine").Build();
        private string _sqlitePath = "";

        public Task InitializeAsync() => _pg.StartAsync();

        public async Task DisposeAsync()
        {
            await _pg.DisposeAsync();
            SqliteConnection.ClearAllPools();
            try { if (File.Exists(_sqlitePath)) File.Delete(_sqlitePath); } catch { /* best-effort */ }
        }

        // A SQLite source whose physical types mirror EF's SQLite mapping: bool->INTEGER,
        // DateTime/decimal/Guid->TEXT, with an INTEGER identity primary key.
        private async Task BuildSqliteSourceAsync()
        {
            _sqlitePath = Path.Combine(Path.GetTempPath(), $"migrate_src_{Guid.NewGuid():N}.db");
            await using var conn = new SqliteConnection($"Data Source={_sqlitePath}");
            await conn.OpenAsync();
            await using (var cmd = conn.CreateCommand())
            {
                cmd.CommandText = @"
                    CREATE TABLE Widgets (
                        Id INTEGER PRIMARY KEY AUTOINCREMENT,
                        Name TEXT NOT NULL,
                        IsActive INTEGER NOT NULL,
                        CreatedUtc TEXT NOT NULL,
                        Price TEXT NOT NULL,
                        Ref TEXT NOT NULL
                    );
                    INSERT INTO Widgets (Name, IsActive, CreatedUtc, Price, Ref) VALUES
                        ('alpha', 1, '2026-06-15T10:34:00.000Z', '19.95', '3f2504e0-4f89-41d3-9a0c-0305e82c3301'),
                        ('beta', 0, '2026-01-02T00:00:00.000Z', '0', 'a1b2c3d4-0000-0000-0000-000000000099');
                    CREATE TABLE __EFMigrationsHistory (MigrationId TEXT PRIMARY KEY, ProductVersion TEXT);
                    INSERT INTO __EFMigrationsHistory VALUES ('20260101_Init', '10.0.0');
                ";
                await cmd.ExecuteNonQueryAsync();
            }
        }

        private async Task CreatePostgresSchemaAsync()
        {
            await using var conn = new NpgsqlConnection(_pg.GetConnectionString());
            await conn.OpenAsync();
            await using var cmd = conn.CreateCommand();
            // EF's Postgres mapping for the same model: boolean / timestamp / numeric / uuid, identity PK.
            cmd.CommandText = @"
                CREATE TABLE ""Widgets"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""Name"" text NOT NULL,
                    ""IsActive"" boolean NOT NULL,
                    ""CreatedUtc"" timestamp with time zone NOT NULL,
                    ""Price"" numeric NOT NULL,
                    ""Ref"" uuid NOT NULL
                );";
            await cmd.ExecuteNonQueryAsync();
        }

        [Fact]
        public async Task Migrate_CoercesTypes_PreservesKeys_AndVerifies()
        {
            await BuildSqliteSourceAsync();
            await CreatePostgresSchemaAsync();

            var result = await DatabaseMigrationService.MigrateDatabaseAsync(
                _sqlitePath, _pg.GetConnectionString(), dryRun: false, NullLogger.Instance, "Test");

            Assert.True(result.Success);
            Assert.Equal(2, result.RowsPerTable["Widgets"]);
            // __EFMigrationsHistory is intentionally not copied.
            Assert.DoesNotContain("__EFMigrationsHistory", result.RowsPerTable.Keys);

            await using var conn = new NpgsqlConnection(_pg.GetConnectionString());
            await conn.OpenAsync();

            // Types coerced and primary keys preserved.
            await using (var cmd = conn.CreateCommand())
            {
                cmd.CommandText = @"SELECT ""IsActive"", ""Price"", ""Ref"" FROM ""Widgets"" WHERE ""Id"" = 1;";
                await using var r = await cmd.ExecuteReaderAsync();
                Assert.True(await r.ReadAsync());
                Assert.True(r.GetBoolean(0));
                Assert.Equal(19.95m, r.GetDecimal(1));
                Assert.Equal(Guid.Parse("3f2504e0-4f89-41d3-9a0c-0305e82c3301"), r.GetGuid(2));
            }

            // Identity sequence was advanced past the copied keys: a default insert lands at 3.
            await using (var cmd = conn.CreateCommand())
            {
                cmd.CommandText =
                    @"INSERT INTO ""Widgets"" (""Name"", ""IsActive"", ""CreatedUtc"", ""Price"", ""Ref"")
                      VALUES ('gamma', true, now(), 1, gen_random_uuid()) RETURNING ""Id"";";
                var id = Convert.ToInt64(await cmd.ExecuteScalarAsync());
                Assert.Equal(3, id);
            }
        }

        [Fact]
        public async Task DryRun_WritesNothing_ButReportsCounts()
        {
            await BuildSqliteSourceAsync();
            await CreatePostgresSchemaAsync();

            var result = await DatabaseMigrationService.MigrateDatabaseAsync(
                _sqlitePath, _pg.GetConnectionString(), dryRun: true, NullLogger.Instance, "Test");

            Assert.True(result.Success);
            Assert.Equal(2, result.RowsPerTable["Widgets"]);

            await using var conn = new NpgsqlConnection(_pg.GetConnectionString());
            await conn.OpenAsync();
            await using var cmd = conn.CreateCommand();
            cmd.CommandText = @"SELECT COUNT(*) FROM ""Widgets"";";
            Assert.Equal(0L, Convert.ToInt64(await cmd.ExecuteScalarAsync()));
        }

        [Fact]
        public async Task MissingTargetTable_FailsClosed()
        {
            await BuildSqliteSourceAsync();
            // Deliberately do NOT create the Postgres schema.

            var result = await DatabaseMigrationService.MigrateDatabaseAsync(
                _sqlitePath, _pg.GetConnectionString(), dryRun: false, NullLogger.Instance, "Test");

            Assert.False(result.Success);
        }

        [Fact]
        public async Task Migrate_RealOrchestratorSchemas_MapsFoldedPostgresIdentifiers()
        {
            _sqlitePath = Path.Combine(Path.GetTempPath(), $"migrate_orch_{Guid.NewGuid():N}.db");
            var source = new SQLiteJobHistoryStore(_sqlitePath);
            await source.InitializeAsync();
            await source.SaveJobAsync(new JobDefinition(
                "nightly", "PRINT 'ok';", 1, "DAY", "01:00", null, null, true));
            var historyId = await source.LogJobStartAsync("nightly");
            await source.LogJobEndAsync(historyId, "SUCCESS", rowsProcessed: 7);

            var target = new RelationalJobHistoryStore(
                new NpgsqlOrchestratorDialect(_pg.GetConnectionString()));
            await target.InitializeAsync();

            var result = await DatabaseMigrationService.MigrateDatabaseAsync(
                _sqlitePath, _pg.GetConnectionString(), dryRun: false, NullLogger.Instance, "Orchestrator");

            Assert.True(result.Success);
            Assert.Equal(1, result.RowsPerTable["Jobs"]);
            Assert.NotNull(await target.GetJobAsync("nightly"));
            var history = Assert.Single(await target.GetHistoryAsync("nightly"));
            Assert.Equal(7, history.RowsProcessed);
        }

        [Fact]
        public async Task DryRun_FailsWhenTargetHasRequiredColumnMissingFromSource()
        {
            await BuildSqliteSourceAsync();
            await CreatePostgresSchemaAsync();

            await using (var conn = new NpgsqlConnection(_pg.GetConnectionString()))
            {
                await conn.OpenAsync();
                await using var cmd = conn.CreateCommand();
                cmd.CommandText = @"ALTER TABLE ""Widgets"" ADD COLUMN ""RequiredValue"" text NOT NULL;";
                await cmd.ExecuteNonQueryAsync();
            }

            var result = await DatabaseMigrationService.MigrateDatabaseAsync(
                _sqlitePath, _pg.GetConnectionString(), dryRun: true, NullLogger.Instance, "Test");

            Assert.False(result.Success);
        }

        [Fact]
        public async Task DryRun_ValidatesSourceValuesAgainstTargetTypes()
        {
            await BuildSqliteSourceAsync();
            await CreatePostgresSchemaAsync();

            await using (var conn = new SqliteConnection($"Data Source={_sqlitePath}"))
            {
                await conn.OpenAsync();
                await using var cmd = conn.CreateCommand();
                cmd.CommandText = "UPDATE Widgets SET Ref = 'not-a-uuid' WHERE Id = 1;";
                await cmd.ExecuteNonQueryAsync();
            }

            await Assert.ThrowsAsync<FormatException>(() =>
                DatabaseMigrationService.MigrateDatabaseAsync(
                    _sqlitePath, _pg.GetConnectionString(), dryRun: true, NullLogger.Instance, "Test"));
        }
    }
}
