<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>ETL-SQL-Report</AssemblyName>
    <RootNamespace>ETL_SQL.ReportBuilder.CLI</RootNamespace>
    <ImplicitUsings>disable</ImplicitUsings>
    <RuntimeIdentifiers>win-x64;linux-x64;osx-arm64</RuntimeIdentifiers>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ETL-SQL.Infrastructure.Sqlite\ETL-SQL.Infrastructure.Sqlite.csproj" />
    <ProjectReference Include="..\ETL-SQL.ReportBuilder\ETL-SQL.ReportBuilder.csproj" />
    <ProjectReference Include="..\ETL-SQL.Reporting\ETL-SQL.Reporting.csproj" />
    <ProjectReference Include="..\ETL-SQL.App\ETL-SQL.App.csproj" />
  </ItemGroup>

</Project>
