/**
 * The browser-side type gate.
 *
 * Runs `tsc --checkJs` over the canonical browser sources (see tsconfig.json at the repository
 * root) and compares the result against a checked-in baseline of findings that were already there
 * when the gate went in. It fails on two things, and only these two:
 *
 *   - a finding that is not in the baseline — new untyped code, or an old file edited into a new
 *     defect. This is the point of the gate.
 *   - a baseline entry that no longer reproduces — the finding was fixed and the entry is stale.
 *     Stale entries are how a baseline quietly stops meaning anything, so removing them is part of
 *     fixing a finding, not a chore for later. `--update` does it for you.
 *
 * The baseline is empty, and that is the point: every one of the 822 findings the sources carried
 * when the gate went in has been worked off, so any finding at all is a new one. The mechanism
 * stays because it is what got the count to zero and what will absorb the next large import
 * without the gate having to be switched off to land it.
 *
 * A finding is identified by file, error code and message — deliberately not by line number, so
 * that editing a file above a known finding does not present it as new.
 *
 * Usage:
 *   node scripts/typecheck-browser.mjs              check (this is what the pre-push gate runs)
 *   node scripts/typecheck-browser.mjs --update     rewrite the baseline from the current state
 *   node scripts/typecheck-browser.mjs --summary    print what is left, by file and by code
 */
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const scriptRoot = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(scriptRoot, '..');
const baselinePath = path.join(repoRoot, 'browser-typecheck-baseline.txt');
const tsc = path.join(scriptRoot, 'typecheck', 'node_modules', 'typescript', 'bin', 'tsc');

const update = process.argv.includes('--update');
const summary = process.argv.includes('--summary');

if (!fs.existsSync(tsc)) {
    console.error('The type-gate toolchain is not installed.');
    console.error('Run:  npm ci --prefix scripts/typecheck');
    process.exit(1);
}

let output = '';
try {
    output = execFileSync(process.execPath, [tsc, '-p', path.join(repoRoot, 'tsconfig.json'), '--pretty', 'false'], {
        cwd: repoRoot,
        encoding: 'utf8',
        stdio: ['ignore', 'pipe', 'pipe'],
    });
} catch (error) {
    // tsc exits non-zero when it reports anything, which is the normal case here.
    output = `${error.stdout ?? ''}${error.stderr ?? ''}`;
    if (!output.trim()) {
        console.error('tsc produced no output and failed. Is the toolchain installed correctly?');
        console.error(error.message);
        process.exit(1);
    }
}

// `path/to/file.js(120,7): error TS2339: Property 'value' does not exist on type 'HTMLElement'.`
// Continuation lines of a multi-line message are indented and belong to the finding above them.
const LINE = /^(.+?)\((\d+),(\d+)\): error (TS\d+): (.*)$/;

/** @type {Array<{file: string, line: number, code: string, message: string}>} */
const findings = [];
for (const raw of output.split(/\r?\n/)) {
    const match = LINE.exec(raw);
    if (!match) continue;
    const [, file, line, , code, message] = match;
    findings.push({
        file: path.relative(repoRoot, path.resolve(repoRoot, file)).replace(/\\/g, '/'),
        line: Number(line),
        code,
        message,
    });
}

// Configuration errors (a bad tsconfig, a missing lib) have no file and would otherwise be
// silently dropped by the parse above.
const configErrors = output.split(/\r?\n/).filter(l => /^error TS\d+:/.test(l));
if (configErrors.length) {
    console.error('tsc could not run:');
    for (const line of configErrors) console.error(`  ${line}`);
    process.exit(1);
}

/** Line numbers move; the finding is the same one. Identity is file + code + message. */
const key = f => `${f.file}\t${f.code}\t${f.message}`;

if (summary) {
    const byFile = new Map();
    const byCode = new Map();
    for (const f of findings) {
        byFile.set(f.file, (byFile.get(f.file) ?? 0) + 1);
        byCode.set(f.code, (byCode.get(f.code) ?? 0) + 1);
    }
    const rank = m => [...m.entries()].sort((a, b) => b[1] - a[1]);
    console.log(`${findings.length} finding(s)\n`);
    console.log('By file:');
    for (const [file, count] of rank(byFile)) console.log(`  ${String(count).padStart(4)}  ${file}`);
    console.log('\nBy code:');
    for (const [code, count] of rank(byCode)) console.log(`  ${String(count).padStart(4)}  ${code}`);
    process.exit(0);
}

const header = `# Browser type-gate baseline — findings that already existed when the gate went in.
#
# Generated by: node scripts/typecheck-browser.mjs --update
#
# One line per finding: <file> TAB <code> TAB <message>. No line numbers, so editing a file above
# a known finding does not make it look new. Repeated identical findings in one file appear once
# with a count.
#
# This file may shrink and must never grow. Adding a line to it by hand is how a gate stops being
# one; fix the finding, then run --update to drop its entry.
`;

function serialize(list) {
    const counts = new Map();
    for (const f of list) counts.set(key(f), (counts.get(key(f)) ?? 0) + 1);
    return header + [...counts.entries()]
        .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))
        .map(([k, count]) => `${count}\t${k}`)
        .join('\n') + '\n';
}

if (update) {
    fs.writeFileSync(baselinePath, serialize(findings));
    console.log(`Baseline updated: ${findings.length} finding(s) recorded in browser-typecheck-baseline.txt`);
    process.exit(0);
}

if (!fs.existsSync(baselinePath)) {
    console.error('browser-typecheck-baseline.txt is missing. Create it with:');
    console.error('  node scripts/typecheck-browser.mjs --update');
    process.exit(1);
}

/** @type {Map<string, number>} */
const baseline = new Map();
for (const raw of fs.readFileSync(baselinePath, 'utf8').split(/\r?\n/)) {
    if (!raw.trim() || raw.startsWith('#')) continue;
    const tab = raw.indexOf('\t');
    baseline.set(raw.slice(tab + 1), Number(raw.slice(0, tab)));
}

/** @type {Map<string, number>} */
const current = new Map();
for (const f of findings) current.set(key(f), (current.get(key(f)) ?? 0) + 1);

const added = [];
for (const [k, count] of current) {
    const allowed = baseline.get(k) ?? 0;
    if (count > allowed) added.push({ k, count, allowed });
}
const stale = [];
for (const [k, allowed] of baseline) {
    const count = current.get(k) ?? 0;
    if (count < allowed) stale.push({ k, count, allowed });
}

const describe = k => {
    const [file, code, message] = k.split('\t');
    return `${file}\n      ${code}: ${message}`;
};

if (added.length) {
    console.error(`\nBrowser type gate: ${added.length} new finding(s).\n`);
    for (const { k, count, allowed } of added) {
        console.error(`  [${count > allowed + 1 || allowed > 0 ? `${allowed} -> ${count}` : 'new'}] ${describe(k)}\n`);
    }
    console.error('Fix them, or — if the finding is genuinely not fixable here — say why in the');
    console.error('commit and run `node scripts/typecheck-browser.mjs --update`.');
}

if (stale.length) {
    console.error(`\nBrowser type gate: ${stale.length} baseline entr(y/ies) no longer reproduce.\n`);
    for (const { k, count, allowed } of stale) {
        console.error(`  [${allowed} -> ${count}] ${describe(k)}\n`);
    }
    console.error('Good news — these are fixed. Run `node scripts/typecheck-browser.mjs --update`');
    console.error('so the baseline stops claiming them.');
}

if (added.length || stale.length) process.exit(1);

console.log(findings.length === 0
    ? 'browser type gate: clean — 0 findings'
    : `browser type gate: ${findings.length} known finding(s), no new ones`);
