<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>ETL_SQL.Infrastructure.Sqlite</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ETL-SQL.Core\ETL-SQL.Core.csproj" />
  </ItemGroup>

</Project>
