using System.Text;
using System.Text.RegularExpressions;
using ETL_SQL.Portal.Models;

namespace ETL_SQL.Portal.Services;

public sealed class DesignerScriptGenerationService
{
    private const int GridCols = 12;

    public string Generate(DesignerStateDto state)
    {
        var sb = new StringBuilder();
        sb.AppendLine("-- Generated by ETL-SQL Report Designer");
        sb.AppendLine();

        foreach (var ds in state.Datasets ?? [])
        {
            var name = NormalizeDatasetName(ds.Name);
            var query = string.IsNullOrWhiteSpace(ds.Query) ? "SELECT 1 AS Placeholder" : ds.Query.Trim().TrimEnd(';');
            sb.AppendLine($"CREATE DATASET {name} AS (");
            sb.AppendLine($"  {query}");
            sb.AppendLine($");");
            sb.AppendLine();
        }

        int pageNum = 0;
        foreach (var page in state.Pages ?? [])
        {
            pageNum++;
            var pageName = SanitizeName(string.IsNullOrWhiteSpace(page.Name) ? $"Page{pageNum}" : page.Name);
            var visuals = page.Visuals ?? [];

            foreach (var v in visuals)
            {
                sb.AppendLine(GenerateElement(v));
                sb.AppendLine();
            }

            var mode = string.Equals(page.Mode, "Paginated", StringComparison.OrdinalIgnoreCase)
                ? "PAGINATED" : "DASHBOARD";

            if (visuals.Count > 0)
            {
                var structure = BuildStructure(visuals);
                sb.AppendLine($"CREATE PAGE [{pageName}] AS {mode} (");
                sb.AppendLine($"    LAYOUT (");
                sb.AppendLine($"        STRUCTURE = '{EscapeStructure(structure)}',");
                sb.AppendLine($"        MAP (");
                for (int i = 0; i < visuals.Count; i++)
                {
                    var v = visuals[i];
                    var slot = GetSlotLetter(i);
                    var trail = i < visuals.Count - 1 ? "," : "";
                    sb.AppendLine($"            '{slot}' = {SanitizeName(v.Name, v.Id)}{trail}");
                }
                sb.AppendLine($"        )");
                sb.AppendLine($"    )");
                sb.AppendLine($");");
            }
            else
            {
                sb.AppendLine($"CREATE PAGE [{pageName}] AS {mode} ( LAYOUT ( STRUCTURE = '.' ) );");
            }

            sb.AppendLine();
        }

        return sb.ToString();
    }

    private static string GenerateElement(DesignerVisualDto v)
    {
        var sb = new StringBuilder();
        var name = SanitizeName(v.Name, v.Id);
        if (string.Equals(v.Type, "CONTAINER", StringComparison.OrdinalIgnoreCase))
        {
            var containerType = v.Options.TryGetValue("CONTAINER_TYPE", out var ct) ? ct : "BOX";
            sb.AppendLine($"CREATE CONTAINER {name} AS {containerType.ToUpper()} (");
            if (!string.IsNullOrWhiteSpace(v.Title))
                sb.AppendLine($"    TITLE = '{EscapeStr(v.Title)}',");
            sb.Append(");");
        }
        else if (string.Equals(v.Type, "BUTTON", StringComparison.OrdinalIgnoreCase))
        {
            var buttonType = v.Options.TryGetValue("BUTTON_TYPE", out var bt) ? bt : "REFRESH";
            sb.AppendLine($"CREATE BUTTON {name} AS (");
            if (!string.IsNullOrWhiteSpace(v.Title))
                sb.AppendLine($"    TITLE = '{EscapeStr(v.Title)}',");
            sb.AppendLine($"    OPTIONS (BUTTON_TYPE = '{buttonType}'),");
            sb.Append(");");
        }
        else
        {
            sb.AppendLine($"CREATE VISUAL {name} AS {v.Type.ToUpper()} (");
            if (!string.IsNullOrWhiteSpace(v.Title))
                sb.AppendLine($"    TITLE = '{EscapeStr(v.Title)}',");
            if (!string.IsNullOrWhiteSpace(v.Dataset))
                sb.AppendLine($"    SOURCE = {NormalizeDatasetName(v.Dataset)},");
            var mappings = (v.Mappings ?? [])
                .Where(m => !string.IsNullOrWhiteSpace(m.Value))
                .Select(m => $"{m.Key.ToUpper()} = {m.Value}")
                .ToList();
            if (mappings.Count > 0)
                sb.AppendLine($"    MAPPINGS ({string.Join(", ", mappings)}),");

            var layoutOpts = new List<string>();
            if (v.GridColSpan > 0 && v.GridColSpan != 12)
                layoutOpts.Add($"COLSPAN = {v.GridColSpan}");
            if (v.GridRowSpan > 0 && v.GridRowSpan != 4)
                layoutOpts.Add($"ROWSPAN = {v.GridRowSpan}");
            if (v.Options.TryGetValue("WIDTH", out var w) && !string.IsNullOrWhiteSpace(w))
                layoutOpts.Add($"WIDTH = '{EscapeStr(w)}'");
            if (v.Options.TryGetValue("HEIGHT", out var h) && !string.IsNullOrWhiteSpace(h))
                layoutOpts.Add($"HEIGHT = '{EscapeStr(h)}'");
            if (layoutOpts.Count > 0)
                sb.AppendLine($"    LAYOUT ({string.Join(", ", layoutOpts)}),");

            sb.Append(");");
        }
        return sb.ToString().TrimEnd();
    }

    private static string GetSlotLetter(int index)
    {
        string letter = "";
        int idx = index;
        while (idx >= 0)
        {
            letter = (char)('A' + (idx % 26)) + letter;
            idx = (idx / 26) - 1;
        }
        return letter;
    }

    private static string BuildStructure(IReadOnlyList<DesignerVisualDto> visuals)
    {
        if (visuals.Count == 0) return ".";
        int maxRow = visuals.Max(v => v.GridRow + v.GridRowSpan - 1);
        int usedCols = Math.Min(GridCols, visuals.Max(v => v.GridCol + v.GridColSpan - 1));
        var grid = new string[maxRow, usedCols];
        for (int r = 0; r < maxRow; r++)
            for (int c = 0; c < usedCols; c++)
                grid[r, c] = ".";

        for (int i = 0; i < visuals.Count; i++)
        {
            var v = visuals[i];
            var slot = GetSlotLetter(i);
            for (int r = v.GridRow - 1; r < v.GridRow - 1 + v.GridRowSpan && r < maxRow; r++)
                for (int c = v.GridCol - 1; c < v.GridCol - 1 + v.GridColSpan && c < usedCols; c++)
                    grid[r, c] = slot;
        }

        // 1. Compress horizontal contiguous identical slot cells per row
        var compressedRows = new List<string>(maxRow);
        for (int r = 0; r < maxRow; r++)
        {
            var rowSlots = new List<string>();
            for (int c = 0; c < usedCols; c++)
            {
                var slot = grid[r, c];
                if (rowSlots.Count == 0 || rowSlots[^1] != slot)
                    rowSlots.Add(slot);
            }
            compressedRows.Add(string.Join(" ", rowSlots));
        }

        // 2. Deduplicate consecutive identical rows vertically
        var dedupedRows = new List<string>(maxRow);
        foreach (var rowStr in compressedRows)
        {
            if (dedupedRows.Count == 0 || dedupedRows[^1] != rowStr)
                dedupedRows.Add(rowStr);
        }

        return string.Join(" / ", dedupedRows);
    }

    private static string SanitizeName(string name, string? fallback = null)
    {
        var input = string.IsNullOrWhiteSpace(name) ? fallback : name;
        if (string.IsNullOrWhiteSpace(input)) return "visual1";
        var safe = Regex.Replace(input.Trim(), @"[^a-zA-Z0-9_]", "_");
        if (!char.IsLetter(safe[0])) safe = "v_" + safe;
        return safe;
    }

    private static string NormalizeDatasetName(string name)
    {
        var trimmed = (name ?? "").Trim();
        if (trimmed.StartsWith("&", StringComparison.Ordinal) || trimmed.StartsWith("#", StringComparison.Ordinal))
            trimmed = trimmed[1..];
        return "&" + SanitizeName(trimmed);
    }

    private static string EscapeStr(string s) => s.Replace("'", "''");

    private static string EscapeStructure(string s) => s.Replace("'", "''");
}
