// A fetch-like function that answers the report designer's endpoints with canned
// data, so createDesigner() runs in the sandbox with no portal server.
//
// createDesigner calls:
//   POST /api/designer/generate {designState}  -> { script }
//   POST /api/designer/parse    {script}       -> { designState }
//   (save endpoints are bypassed via opts.onSaveScript in the story)
//
// The parse round-trip just echoes the seed state — a faithful script↔state parse
// is the real DesignerController's job; here we only need the UI to round-trip.
export function makeMockApi(seedState) {
  return async (url, init) => {
    const path = String(url).replace(/^https?:\/\/[^/]+/, '').replace(/\?.*$/, '');
    let body = {};
    try { body = init?.body ? JSON.parse(init.body) : {}; } catch { /* ignore */ }

    let data = {};
    if (path.endsWith('/api/designer/generate')) {
      data = { script: generateMockScript(body.designState ?? seedState) };
    } else if (path.endsWith('/api/designer/parse')) {
      data = { designState: seedState };
    } else if (path.endsWith('/api/scripts/upload')) {
      data = { path: 'sandbox/' + (body.fileName || 'report.rptsql') };
    } else if (path.endsWith('/api/reports') || path.includes('/script-content')) {
      data = { id: 1, ok: true };
    }

    return {
      ok: true,
      status: 200,
      json: async () => data,
      text: async () => JSON.stringify(data),
    };
  };
}

function sanitizeName(name) {
  if (!name) return 'visual1';
  let safe = name.trim().replace(/[^a-zA-Z0-9_]/g, '_');
  if (!/^[a-zA-Z]/.test(safe)) safe = 'v_' + safe;
  return safe;
}

function buildStructure(visuals) {
  if (!visuals || visuals.length === 0) return '.';
  const maxRow = Math.max(...visuals.map(v => (v.gridRow || 1) + (v.gridRowSpan || 4) - 1));
  const maxCol = Math.max(...visuals.map(v => (v.gridCol || 1) + (v.gridColSpan || 12) - 1));
  const usedCols = Math.min(12, maxCol);
  
  const grid = Array.from({ length: maxRow }, () => Array(usedCols).fill('.'));
  
  for (const v of visuals) {
    const slot = sanitizeName(v.name);
    const startRow = (v.gridRow || 1) - 1;
    const endRow = startRow + (v.gridRowSpan || 4);
    const startCol = (v.gridCol || 1) - 1;
    const endCol = startCol + (v.gridColSpan || 12);
    
    for (let r = startRow; r < endRow && r < maxRow; r++) {
      for (let c = startCol; c < endCol && c < usedCols; c++) {
        grid[r][c] = slot;
      }
    }
  }
  
  return grid.map(row => row.join(' ')).join(' / ');
}

function generateMockScript(state) {
  const out = ['-- generated by the sandbox mock (not the real DesignerController)'];
  for (const ds of (state?.datasets ?? [])) {
    const name = ds.name.startsWith('&') ? ds.name : '&' + ds.name;
    out.push(`CREATE DATASET ${name} AS (\n  ${ds.query}\n);`);
  }
  for (const p of (state?.pages ?? [])) {
    out.push('');
    for (const v of (p.visuals ?? [])) {
      const vName = sanitizeName(v.name);
      if (v.type === 'CONTAINER') {
        const containerType = v.options?.CONTAINER_TYPE || 'BOX';
        out.push(`CREATE CONTAINER ${vName} AS ${containerType.toUpperCase()} (\n    TITLE = '${v.title || ''}',\n);`);
      } else if (v.type === 'BUTTON') {
        const buttonType = v.options?.BUTTON_TYPE || 'REFRESH';
        out.push(`CREATE BUTTON ${vName} AS (\n    TITLE = '${v.title || ''}',\n    OPTIONS (BUTTON_TYPE = '${buttonType}'),\n);`);
      } else {
        const maps = Object.entries(v.mappings ?? {})
          .filter(([_, c]) => c)
          .map(([k, c]) => `${k} = ${c}`)
          .join(', ');
        const dsName = v.dataset ? (v.dataset.startsWith('&') ? v.dataset : '&' + v.dataset) : '&sales';
        out.push(`CREATE VISUAL ${vName} AS ${v.type} (\n    SOURCE = ${dsName}${maps ? `,\n    MAPPINGS (${maps})` : ''},\n    TITLE = '${v.title || v.name}'\n);`);
      }
    }
    const structure = buildStructure(p.visuals);
    const mapEntries = (p.visuals ?? []).map(v => {
      const slot = sanitizeName(v.name);
      return `            '${slot}' = ${sanitizeName(v.name)}`;
    }).join(',\n');

    out.push(`CREATE PAGE [${sanitizeName(p.name)}] AS DASHBOARD (\n    LAYOUT (\n        STRUCTURE = '${structure}',\n        MAP (\n${mapEntries}\n        )\n    )\n);`);
  }
  return out.join('\n');
}

