// A fetch-like function that answers the report designer's endpoints with canned
// data, so createDesigner() runs in the sandbox with no portal server.
//
// createDesigner calls:
//   POST /api/designer/generate {designState}  -> { script }
//   POST /api/designer/parse    {script}       -> { designState }
//   (save endpoints are bypassed via opts.onSaveScript in the story)
//
// The parse round-trip just echoes the seed state — a faithful script↔state parse
// is the real DesignerController's job; here we only need the UI to round-trip.
export function makeMockApi(seedState) {
  return async (url, init) => {
    const path = String(url).replace(/^https?:\/\/[^/]+/, '').replace(/\?.*$/, '');
    let body = {};
    try { body = init?.body ? JSON.parse(init.body) : {}; } catch { /* ignore */ }

    let data = {};
    if (path.endsWith('/api/designer/generate')) {
      data = { script: generateMockScript(body.designState ?? seedState) };
    } else if (path.endsWith('/api/designer/parse')) {
      data = { designState: seedState };
    } else if (path.endsWith('/api/scripts/upload')) {
      data = { path: 'sandbox/' + (body.fileName || 'report.rptsql') };
    } else if (path.endsWith('/api/reports') || path.includes('/script-content')) {
      data = { id: 1, ok: true };
    }

    return {
      ok: true,
      status: 200,
      json: async () => data,
      text: async () => JSON.stringify(data),
    };
  };
}

function generateMockScript(state) {
  const out = ['-- generated by the sandbox mock (not the real DesignerController)'];
  for (const ds of (state?.datasets ?? []))
    out.push(`CREATE DATASET &${ds.name} AS (${ds.query});`);
  for (const p of (state?.pages ?? [])) {
    out.push('');
    for (const v of (p.visuals ?? [])) {
      const maps = Object.entries(v.mappings ?? {}).map(([k, c]) => `${k} = ${c}`).join(', ');
      out.push(`CREATE VISUAL ${v.id} AS ${v.type} ( SOURCE = &${v.dataset || 'sales'}${maps ? `, MAPPINGS (${maps})` : ''}, TITLE = '${v.title || v.id}' );`);
    }
    out.push(`CREATE PAGE ${p.name} AS DASHBOARD( STRUCTURE = 'A', MAP ( ... ) );`);
  }
  return out.join('\n');
}
