using System.Collections.Generic;
using System.Data.Common;
using System.Threading;
using System.Threading.Tasks;
using Npgsql;

namespace ETL_SQL.Orchestrator.Storage
{
    /// <summary>
    /// PostgreSQL dialect for the relational Orchestrator store (Practical HA). Keeps the store's SQL
    /// portable: a case-insensitive <c>nocase</c> collation makes <c>COLLATE NOCASE</c> resolve, identity
    /// columns replace SQLite's AUTOINCREMENT, and identity is read back with RETURNING. Unquoted
    /// identifiers fold to lower case in PostgreSQL — the store's reads use case-insensitive
    /// <c>GetOrdinal</c> and the column sweep compares case-insensitively, so no quoting is needed.
    /// </summary>
    public sealed class NpgsqlOrchestratorDialect : IOrchestratorStoreDialect
    {
        private readonly string _connectionString;

        public NpgsqlOrchestratorDialect(string connectionString) => _connectionString = connectionString;

        public DbConnection CreateConnection() => new NpgsqlConnection(_connectionString);

        // ICU nondeterministic collation → case-insensitive equality/ordering for COLLATE NOCASE.
        public string CollationDdl =>
            "CREATE COLLATION IF NOT EXISTS nocase (provider = icu, locale = 'und-u-ks-level2', deterministic = false);";

        public string AutoIncrementPrimaryKey => "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY";

        public async Task<HashSet<string>> GetColumnNamesAsync(DbConnection connection, string table, CancellationToken ct = default)
        {
            var columns = new HashSet<string>(System.StringComparer.OrdinalIgnoreCase);
            using var cmd = connection.CreateCommand();
            cmd.CommandText =
                "SELECT column_name FROM information_schema.columns " +
                "WHERE table_schema = current_schema() AND lower(table_name) = lower(@table);";
            cmd.AddParam("@table", table);
            using var reader = await cmd.ExecuteReaderAsync(ct);
            while (await reader.ReadAsync(ct)) columns.Add(reader.GetString(0));
            return columns;
        }

        public string InsertReturningId(string insertWithoutSemicolon, string idColumn) =>
            insertWithoutSemicolon + " RETURNING " + idColumn + ";";
    }
}
